using Avalonia.Controls;
using Avalonia.Media;
using ExcelToSQLite.Models;
using ExcelToSQLite.Services;
using ReactiveUI;
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.IO;
using System.Linq;
using System.Reactive;
using System.Reactive.Disposables;
using System.Reactive.Linq;
using System.Threading;
using System.Threading.Tasks;
using ExcelToSQLite.Helpers;
using Avalonia.Threading;

namespace ExcelToSQLite.ViewModels;

/// <summary>
/// Excel数据导入 ViewModel - 实现 ICleanupPage 和 IDisposable 以确保资源正确释放
/// </summary>
public class ExcelDataViewModel : ReactiveObject, ICleanupPage, IDisposable
{
    private readonly ExcelService? _excelService;
    private readonly DatabaseService? _databaseService;
    private readonly AnalysisBatchService? _batchService;
    private readonly DataDictionaryService? _dictionaryService;
    private readonly SemaphoreSlim _lock = new SemaphoreSlim(1, 1);
    private readonly CompositeDisposable _subscriptions = new CompositeDisposable();
    private CancellationTokenSource? _cts;
    
    private Window? _parentWindow;
    private bool _disposed;
    private bool _isCleaned;
    private bool _isLoading;
    private string _loadingMessage = string.Empty;
    
    // 文件相关
    private string _filePath = string.Empty;
    private ObservableCollection<string> _selectedFiles = new();
    private int _fileCount;
    private int _totalRows;
    private int _columnCount;
    private string? _lastOpenDirectory;
    
    // 表名相关
    private string _tableName = string.Empty;
    private string _tableNameInfo = string.Empty;
    private string _tableNameValidation = string.Empty;
    private IBrush _validationColor = new SolidColorBrush(Colors.Green);
    private bool _showValidation = false;
    private bool _isAutoGenerated = false;
    private string? _currentFileName;
    
    // 状态
    private bool _canImport;
    private string _statusMessage = string.Empty;
    private IBrush _statusColor = new SolidColorBrush(Colors.Transparent);
    private bool _showStatus = false;
    private bool _showImportStats;
    private string _importStatsText = string.Empty;
    
    // 批次
    private ObservableCollection<AnalysisBatch> _batches = new();
    private AnalysisBatch? _selectedBatch;
    private string _batchInfo = string.Empty;
    
    // 数据字典
    private ObservableCollection<DataDictionary> _dataDictionaries = new();
    private DataDictionary? _selectedDictionary;
    private string _dictionaryInfo = string.Empty;
    private bool _useDictionary = false;

    public ExcelDataViewModel()
    {
        try
        {
            _excelService = new ExcelService();
            _databaseService = DatabaseService.Instance;
            _batchService = new AnalysisBatchService();
            _dictionaryService = new DataDictionaryService();
            
            SelectFileCommand = ReactiveCommand.CreateFromTask(SelectFileAsync);
            GenerateTableNameCommand = ReactiveCommand.Create(GenerateTableName);
            ImportCommand = ReactiveCommand.CreateFromTask(ImportAsync, this.WhenAnyValue(x => x.CanImport));
            ClearCommand = ReactiveCommand.Create(Clear);
            RefreshBatchesCommand = ReactiveCommand.CreateFromTask(LoadBatchesAsync);
            RefreshDictionariesCommand = ReactiveCommand.CreateFromTask(LoadDictionariesAsync);
            
            // 订阅命令异常
            SelectFileCommand.ThrownExceptions
                .ObserveOn(RxApp.MainThreadScheduler)
                .Subscribe(ex =>
                {
                    SetStatus($"选择文件失败: {ex.Message}", new SolidColorBrush(Colors.Red));
                })
                .DisposeWith(_subscriptions);

            ImportCommand.ThrownExceptions
                .ObserveOn(RxApp.MainThreadScheduler)
                .Subscribe(ex =>
                {
                    SetStatus($"导入失败: {ex.Message}", new SolidColorBrush(Colors.Red));
                })
                .DisposeWith(_subscriptions);

            CanImport = false;
            
            // 监听表名变化，进行验证
            this.WhenAnyValue(x => x.TableName)
                .Subscribe(_ => ValidateTableName())
                .DisposeWith(_subscriptions);
            
            // 监听数据字典选择变化
            this.WhenAnyValue(x => x.SelectedDictionary)
                .Subscribe(_ => 
                {
                    if (UseDictionary && SelectedDictionary != null && !string.IsNullOrEmpty(_currentFileName))
                    {
                        GenerateTableName();
                    }
                })
                .DisposeWith(_subscriptions);
            
            // 监听是否使用数据字典
            this.WhenAnyValue(x => x.UseDictionary)
                .Subscribe(_ => 
                {
                    if (UseDictionary && SelectedDictionary != null && !string.IsNullOrEmpty(_currentFileName))
                    {
                        GenerateTableName();
                    }
                    else if (!UseDictionary && !string.IsNullOrEmpty(_currentFileName))
                    {
                        GenerateTableName();
                    }
                })
                .DisposeWith(_subscriptions);
            
            // 启动异步初始化
            _ = InitializeAsync();
            
        }
        catch (Exception ex)
        {
            SetStatusSafe($"初始化失败: {ex.Message}", new SolidColorBrush(Colors.Red));
        }
    }

    #region 属性

    public bool IsLoading
    {
        get => _isLoading;
        set => this.RaiseAndSetIfChanged(ref _isLoading, value);
    }

    public string LoadingMessage
    {
        get => _loadingMessage;
        set => this.RaiseAndSetIfChanged(ref _loadingMessage, value);
    }

    public string FilePath
    {
        get => _filePath;
        set => this.RaiseAndSetIfChanged(ref _filePath, value);
    }

    public ObservableCollection<string> SelectedFiles
    {
        get => _selectedFiles;
        set => this.RaiseAndSetIfChanged(ref _selectedFiles, value);
    }

    public int FileCount
    {
        get => _fileCount;
        set => this.RaiseAndSetIfChanged(ref _fileCount, value);
    }

    public int TotalRows
    {
        get => _totalRows;
        set => this.RaiseAndSetIfChanged(ref _totalRows, value);
    }

    public int ColumnCount
    {
        get => _columnCount;
        set => this.RaiseAndSetIfChanged(ref _columnCount, value);
    }

    public string TableName
    {
        get => _tableName;
        set
        {
            this.RaiseAndSetIfChanged(ref _tableName, value);
            if (!string.IsNullOrEmpty(value))
            {
                _isAutoGenerated = false;
            }
        }
    }

    public string TableNameInfo
    {
        get => _tableNameInfo;
        set => this.RaiseAndSetIfChanged(ref _tableNameInfo, value);
    }

    public string TableNameValidation
    {
        get => _tableNameValidation;
        set => this.RaiseAndSetIfChanged(ref _tableNameValidation, value);
    }

    public IBrush ValidationColor
    {
        get => _validationColor;
        set => this.RaiseAndSetIfChanged(ref _validationColor, value);
    }

    public bool ShowValidation
    {
        get => _showValidation;
        set => this.RaiseAndSetIfChanged(ref _showValidation, value);
    }

    public bool CanImport
    {
        get => _canImport;
        set => this.RaiseAndSetIfChanged(ref _canImport, value);
    }

    public string StatusMessage
    {
        get => _statusMessage;
        set => this.RaiseAndSetIfChanged(ref _statusMessage, value);
    }

    public IBrush StatusColor
    {
        get => _statusColor;
        set => this.RaiseAndSetIfChanged(ref _statusColor, value);
    }

    public bool ShowStatus
    {
        get => _showStatus;
        set => this.RaiseAndSetIfChanged(ref _showStatus, value);
    }

    public bool ShowImportStats
    {
        get => _showImportStats;
        set => this.RaiseAndSetIfChanged(ref _showImportStats, value);
    }

    public string ImportStatsText
    {
        get => _importStatsText;
        set => this.RaiseAndSetIfChanged(ref _importStatsText, value);
    }

    public ObservableCollection<AnalysisBatch> Batches
    {
        get => _batches;
        set => this.RaiseAndSetIfChanged(ref _batches, value);
    }

    public AnalysisBatch? SelectedBatch
    {
        get => _selectedBatch;
        set
        {
            this.RaiseAndSetIfChanged(ref _selectedBatch, value);
            if (value != null)
            {
                var createdTime = value.CreatedAt.ToString("yyyy-MM-dd HH:mm");
                BatchInfo = $"已选批次: {value.Name} (创建: {createdTime})";
                if (!string.IsNullOrEmpty(_currentFileName))
                {
                    GenerateTableName();
                }
            }
            else
            {
                BatchInfo = "请选择批次";
            }
        }
    }

    public string BatchInfo
    {
        get => _batchInfo;
        set => this.RaiseAndSetIfChanged(ref _batchInfo, value);
    }

    public ObservableCollection<DataDictionary> DataDictionaries
    {
        get => _dataDictionaries;
        set => this.RaiseAndSetIfChanged(ref _dataDictionaries, value);
    }

    public DataDictionary? SelectedDictionary
    {
        get => _selectedDictionary;
        set
        {
            this.RaiseAndSetIfChanged(ref _selectedDictionary, value);
            if (value != null)
            {
                DictionaryInfo = $"已选字典: {value.Name} (表名: {(string.IsNullOrEmpty(value.TableName) ? "使用文件名" : value.TableName)})";
                if (UseDictionary && !string.IsNullOrEmpty(_currentFileName))
                {
                    GenerateTableName();
                }
            }
            else
            {
                DictionaryInfo = "未选择数据字典";
            }
        }
    }

    public string DictionaryInfo
    {
        get => _dictionaryInfo;
        set => this.RaiseAndSetIfChanged(ref _dictionaryInfo, value);
    }

    public bool UseDictionary
    {
        get => _useDictionary;
        set
        {
            this.RaiseAndSetIfChanged(ref _useDictionary, value);
            if (!string.IsNullOrEmpty(_currentFileName))
            {
                GenerateTableName();
            }
        }
    }

    #endregion

    #region 命令

    public ReactiveCommand<Unit, Unit> SelectFileCommand { get; } = null!;
    public ReactiveCommand<Unit, Unit> GenerateTableNameCommand { get; } = null!;
    public ReactiveCommand<Unit, Unit> ImportCommand { get; } = null!;
    public ReactiveCommand<Unit, Unit> ClearCommand { get; } = null!;
    public ReactiveCommand<Unit, Unit> RefreshBatchesCommand { get; } = null!;
    public ReactiveCommand<Unit, Unit> RefreshDictionariesCommand { get; } = null!;

    #endregion

    #region 公共方法

    public void SetParentWindow(Window window)
    {
        _parentWindow = window;
    }

    #endregion

    #region 初始化

    private async Task InitializeAsync()
    {
        if (_disposed || _isCleaned) return;

        await _lock.WaitAsync();
        try
        {
            if (_disposed || _isCleaned) return;

            _cts = new CancellationTokenSource();
            var token = _cts.Token;

            var loadBatchesTask = LoadBatchesAsync();
            var loadDictionariesTask = LoadDictionariesAsync();

            await Task.WhenAll(loadBatchesTask, loadDictionariesTask);

            if (!token.IsCancellationRequested && !_disposed && !_isCleaned)
            {
                SetStatus("初始化完成", new SolidColorBrush(Colors.Green));
            }

        }
        catch (OperationCanceledException)
        {
        }
        catch (Exception ex)
        {
            await SetStatusAsync($"初始化失败: {ex.Message}", new SolidColorBrush(Colors.Red));
        }
        finally
        {
            _lock.Release();
        }
    }

    #endregion

    #region 数据加载

    private async Task LoadBatchesAsync()
    {
        if (_disposed || _isCleaned) return;
        if (_batchService == null) return;

        try
        {
            await ThreadingHelper.RunOnUIThreadAsync(() =>
            {
                if (_disposed || _isCleaned) return;
                IsLoading = true;
                LoadingMessage = "正在加载批次...";
                SetStatus("正在加载批次...", new SolidColorBrush(Colors.Orange));
            });

            var list = await _batchService.GetAllAsync(1000);
            var sortedList = list.OrderByDescending(b => b.CreatedAt).ToList();
            
            await ThreadingHelper.RunOnUIThreadAsync(() =>
            {
                if (_disposed || _isCleaned) return;
                Batches = new ObservableCollection<AnalysisBatch>(sortedList);
            
                if (Batches.Count > 0)
                {
                    SelectedBatch = Batches[0];
                    BatchInfo = $"共 {Batches.Count} 个批次，已选择最新的批次: {SelectedBatch.Name}";
                
                    if (!string.IsNullOrEmpty(_currentFileName))
                    {
                        GenerateTableName();
                    }
                }
                else
                {
                    BatchInfo = "暂无批次，请创建批次";
                    SelectedBatch = null;
                }
                
                IsLoading = false;
                LoadingMessage = string.Empty;
                SetStatus("批次加载完成", new SolidColorBrush(Colors.Green));
            });
        }
        catch (Exception ex)
        {
            await ThreadingHelper.RunOnUIThreadAsync(() =>
            {
                if (_disposed || _isCleaned) return;
                SetStatus($"加载批次失败: {ex.Message}", new SolidColorBrush(Colors.Red));
                BatchInfo = "加载批次失败";
                SelectedBatch = null;
                IsLoading = false;
                LoadingMessage = string.Empty;
            });
        }
    }

    private async Task LoadDictionariesAsync()
    {
        if (_disposed || _isCleaned) return;
        if (_dictionaryService == null) return;

        try
        {
            await _dictionaryService.InitializeAsync();
            var list = await _dictionaryService.GetAllAsync();
            
            await ThreadingHelper.RunOnUIThreadAsync(() =>
            {
                if (_disposed || _isCleaned) return;
                DataDictionaries = new ObservableCollection<DataDictionary>(list);
                
                if (DataDictionaries.Count > 0)
                {
                    SelectedDictionary = DataDictionaries[0];
                    DictionaryInfo = $"已加载 {DataDictionaries.Count} 个数据字典";
                }
                else
                {
                    DictionaryInfo = "暂无数据字典，请先在数据字典页面创建";
                    SelectedDictionary = null;
                }
            });
        }
        catch (Exception ex)
        {
            await ThreadingHelper.RunOnUIThreadAsync(() =>
            {
                if (_disposed || _isCleaned) return;
                SetStatus($"加载数据字典失败: {ex.Message}", new SolidColorBrush(Colors.Red));
                DictionaryInfo = "加载数据字典失败";
            });
        }
    }

    #endregion

    #region 文件选择

    private async Task SelectFileAsync()
    {
        if (_disposed || _isCleaned) return;

        CancelCurrentOperation();

        try
        {
            var window = GetWindow();
            if (window == null)
            {
                await ShowMessageBoxAsync("无法获取窗口句柄");
                return;
            }

            var filePaths = await OpenMultipleExcelFilesAsync(window, "选择Excel文件（可多选）");

            if (filePaths != null && filePaths.Count > 0)
            {
                if (filePaths.Count > 0)
                {
                    _lastOpenDirectory = Path.GetDirectoryName(filePaths[0]);
                }

                var primaryFilePath = filePaths[0];

                await ThreadingHelper.RunOnUIThreadAsync(() =>
                {
                    if (_disposed || _isCleaned) return;
                    FilePath = primaryFilePath;
                    _currentFileName = Path.GetFileNameWithoutExtension(primaryFilePath);
                    SelectedFiles = new ObservableCollection<string>(filePaths.Select(f => Path.GetFileName(f) ?? f));
                    FileCount = filePaths.Count;
                    GenerateTableName();
                });

                await ParseFileInfoAsync();
            }
        }
        catch (OperationCanceledException)
        {
        }
        catch (Exception ex)
        {
            await ShowMessageBoxAsync($"选择文件失败: {ex.Message}");
        }
    }

    private async Task<List<string>?> OpenMultipleExcelFilesAsync(Window? parent, string title)
    {
        if (parent == null || !parent.IsVisible || parent.WindowState == WindowState.Minimized)
            return null;

        var storageProvider = parent.StorageProvider;
        if (storageProvider == null) return null;

        var options = new Avalonia.Platform.Storage.FilePickerOpenOptions
        {
            Title = title,
            AllowMultiple = true,
            SuggestedStartLocation = !string.IsNullOrEmpty(_lastOpenDirectory) 
                ? await storageProvider.TryGetFolderFromPathAsync(new Uri(_lastOpenDirectory))
                : null,
            FileTypeFilter = new List<Avalonia.Platform.Storage.FilePickerFileType>
            {
                new("Excel 文件 (*.xlsx, *.xls)")
                {
                    Patterns = new List<string> { "*.xlsx", "*.xls" }
                },
                new("所有文件 (*.*)")
                {
                    Patterns = new List<string> { "*" }
                }
            }
        };

        try
        {
            using var cts = new CancellationTokenSource(TimeSpan.FromSeconds(30));
            var files = await storageProvider.OpenFilePickerAsync(options).WaitAsync(cts.Token);
            if (files != null && files.Count > 0)
            {
                return files.Select(f => f.Path?.LocalPath ?? f.Name).ToList();
            }
        }
        catch
        {
        }

        return null;
    }

    #endregion

    #region 文件信息解析

    private async Task ParseFileInfoAsync()
    {
        if (_disposed || _isCleaned || string.IsNullOrEmpty(FilePath)) return;
        if (_excelService == null) return;

        try
        {
            await ThreadingHelper.RunOnUIThreadAsync(() =>
            {
                if (_disposed || _isCleaned) return;
                IsLoading = true;
                LoadingMessage = "正在解析文件信息...";
                SetStatus("正在解析文件信息...", new SolidColorBrush(Colors.Orange));
            });

            var data = await _excelService.ReadExcelAsync(FilePath);

            if (data == null || data.Count == 0)
            {
                await ShowMessageBoxAsync("文件为空或格式不正确");
                await ThreadingHelper.RunOnUIThreadAsync(() =>
                {
                    if (!_disposed && !_isCleaned) 
                    {
                        IsLoading = false;
                        LoadingMessage = string.Empty;
                    }
                });
                return;
            }

            await ThreadingHelper.RunOnUIThreadAsync(() =>
            {
                if (_disposed || _isCleaned) return;

                int totalRows = data.Count - 1;
                int totalCols = data[0]?.Count ?? 0;
                TotalRows = totalRows;
                ColumnCount = totalCols;
                
                CanImport = true;
                IsLoading = false;
                LoadingMessage = string.Empty;
                SetStatus($"文件解析成功: {Path.GetFileName(FilePath)}，共 {totalRows} 行数据，{totalCols} 列", new SolidColorBrush(Colors.Green));
            });
        }
        catch (Exception ex)
        {
            await ThreadingHelper.RunOnUIThreadAsync(() =>
            {
                if (_disposed || _isCleaned) return;
                CanImport = false;
                IsLoading = false;
                LoadingMessage = string.Empty;
                SetStatus($"解析失败: {ex.Message}", new SolidColorBrush(Colors.Red));
            });
            await ShowMessageBoxAsync($"解析文件信息失败: {ex.Message}");
        }
    }

    #endregion

    #region 表名生成

    private void GenerateTableName()
    {
        if (_disposed || _isCleaned) return;

        if (string.IsNullOrEmpty(FilePath) || SelectedBatch == null)
        {
            TableName = string.Empty;
            TableNameInfo = "请选择文件和批次后自动生成表名";
            return;
        }

        var fileName = Path.GetFileNameWithoutExtension(FilePath);
        var tablePrefix = SelectedBatch.TablePrefix;
        string generatedName;

        if (UseDictionary && SelectedDictionary != null)
        {
            generatedName = PublicEvent.GetFormatFilename(tablePrefix, fileName, SelectedDictionary.TableName);
        }
        else
        {
            generatedName = PublicEvent.GetFormatFilename(tablePrefix, fileName);
        }

        TableName = generatedName;
        _isAutoGenerated = true;
        ValidateTableName();
    }

    private void ValidateTableName()
    {
        if (_disposed || _isCleaned) return;

        if (string.IsNullOrEmpty(TableName))
        {
            TableNameValidation = "⚠️ 表名不能为空";
            ValidationColor = new SolidColorBrush(Colors.Orange);
            ShowValidation = true;
            return;
        }

        var invalidChars = new[] { ' ', '-', '/', '\\', ':', '*', '?', '"', '<', '>', '|', '\'', ';' };
        if (TableName.IndexOfAny(invalidChars) >= 0)
        {
            TableNameValidation = "❌ 表名包含非法字符，请使用字母、数字和下划线";
            ValidationColor = new SolidColorBrush(Colors.Red);
            ShowValidation = true;
            return;
        }

        if (!char.IsLetter(TableName[0]))
        {
            TableNameValidation = "⚠️ 表名应以字母开头";
            ValidationColor = new SolidColorBrush(Colors.Orange);
            ShowValidation = true;
            return;
        }

        if (TableName.Length > 60)
        {
            TableNameValidation = $"⚠️ 表名过长 ({TableName.Length}/60)，建议缩短";
            ValidationColor = new SolidColorBrush(Colors.Orange);
            ShowValidation = true;
            return;
        }

        var keywords = new[] { "SELECT", "INSERT", "UPDATE", "DELETE", "DROP", "CREATE", "ALTER", "TABLE" };
        if (keywords.Contains(TableName.ToUpper()))
        {
            TableNameValidation = "⚠️ 表名不能是SQL关键字";
            ValidationColor = new SolidColorBrush(Colors.Orange);
            ShowValidation = true;
            return;
        }

        if (_isAutoGenerated)
        {
            TableNameValidation = "✅ 表名有效 (自动生成)";
        }
        else
        {
            TableNameValidation = "✅ 表名有效 (已自定义)";
        }
        ValidationColor = new SolidColorBrush(Colors.Green);
        ShowValidation = true;
    }

    #endregion

    #region 取消操作

    private void CancelCurrentOperation()
    {
        try
        {
            _cts?.Cancel();
            _cts?.Dispose();
            _cts = null;
        }
        catch
        {
        }
    }

    #endregion

    #region 导入

    private async Task ImportAsync()
{
    if (_disposed || _isCleaned) return;
    if (IsLoading) return;
    if (_excelService == null || _databaseService == null) return;

    try
    {
        // 1. 验证基本条件
        if (string.IsNullOrEmpty(FilePath))
        {
            await ShowMessageBoxAsync("请先选择Excel文件");
            return;
        }

        if (SelectedBatch == null)
        {
            await ShowMessageBoxAsync("请先选择分析批次");
            return;
        }

        if (string.IsNullOrEmpty(TableName))
        {
            await ShowMessageBoxAsync("请输入表名或点击'自动生成'");
            return;
        }

        // 2. 验证表名合法性
        if (TableName.IndexOfAny(new[] { ' ', '-', '/', '\\', ':', '*', '?', '"', '<', '>', '|', '\'', ';' }) >= 0)
        {
            await ShowMessageBoxAsync("表名包含非法字符，请使用字母、数字和下划线");
            return;
        }

        if (!char.IsLetter(TableName[0]))
        {
            await ShowMessageBoxAsync("表名应以字母开头");
            return;
        }

        // 3. 确认对话框
        var confirmMessage = $"📊 确认导入数据\n\n" +
                            $"📁 文件数: {FileCount}\n" +
                            $"📋 批次: {SelectedBatch.Name}\n" +
                            $"📝 基础表名: {TableName}\n" +
                            $"📊 数据行数: {TotalRows}\n" +
                            $"📅 创建时间: {SelectedBatch.CreatedAt:yyyy-MM-dd HH:mm}\n";

        if (UseDictionary && SelectedDictionary != null)
        {
            confirmMessage += $"📚 数据字典: {SelectedDictionary.Name}\n";
        }

        confirmMessage += $"\n⚠️ 说明：\n" +
                         $"- 结构相同的文件将合并到同一张表\n" +
                         $"- 结构不同的文件将使用文件名单独建表\n" +
                         $"\n确认继续导入？";
        
        var confirm = await ShowConfirmDialogAsync(confirmMessage);
        if (!confirm) return;

        // 4. 准备导入
        await ThreadingHelper.RunOnUIThreadAsync(() =>
        {
            if (_disposed || _isCleaned) return;
            IsLoading = true;
            LoadingMessage = "正在准备导入...";
            SetStatus("正在导入数据...", new SolidColorBrush(Colors.Orange));
        });

        // 5. 获取所有需要导入的文件
        var filesToImport = GetFilesToImport();
        
        int totalImportedRows = 0;
        var importedTables = new List<string>();
        var importResults = new List<string>();

        // 6. 用于跟踪表结构和表名映射
        var tableStructureMap = new Dictionary<string, List<string>>(); // 表名 -> 列结构签名
        var structureSignatureMap = new Dictionary<string, string>(); // 结构签名 -> 表名
        var usedTableNames = new HashSet<string>();
        
        // 记录第一个文件的列结构作为基准
        List<string>? baseColumns = null;
        string? baseTableName = TableName;

        // 7. 处理每个文件
        for (int idx = 0; idx < filesToImport.Count; idx++)
        {
            var filePath = filesToImport[idx];
            var fileName = Path.GetFileNameWithoutExtension(filePath);
            
            await ThreadingHelper.RunOnUIThreadAsync(() =>
            {
                LoadingMessage = $"正在处理: {fileName} ({idx + 1}/{filesToImport.Count})";
            });

            // 读取Excel数据
            var data = await _excelService.ReadExcelAsync(filePath);
            if (data == null || data.Count <= 1)
            {
                importResults.Add($"⚠️ {Path.GetFileName(filePath)}: 没有数据可导入");
                continue;
            }

            // 提取列名
            var columns = ExtractColumns(data);
            if (columns == null || columns.Count == 0)
            {
                importResults.Add($"⚠️ {Path.GetFileName(filePath)}: 列名无效，跳过");
                continue;
            }

            // 生成结构签名
            var structureSignature = GenerateStructureSignature(columns);
            int columnCount = columns.Count;

            // 8. 确定目标表名（核心逻辑）
            string targetTableName;
            
            // 8.1 第一个文件：使用用户定义的表名
            if (idx == 0)
            {
                targetTableName = baseTableName;
                baseColumns = columns;
                
                // 记录结构和表名映射
                structureSignatureMap[structureSignature] = targetTableName;
                tableStructureMap[targetTableName] = columns;
                usedTableNames.Add(targetTableName);
            }
            // 8.2 检查是否与第一个文件结构一致
            else if (baseColumns != null && AreColumnsEqual(baseColumns, columns))
            {
                targetTableName = baseTableName;
                importResults.Add($"🔄 {Path.GetFileName(filePath)}: 结构与基础表一致，合并到 {targetTableName}");
            }
            // 8.3 检查是否与已处理的其他文件结构一致
            else if (structureSignatureMap.TryGetValue(structureSignature, out var existingTableName))
            {
                targetTableName = existingTableName;
                importResults.Add($"🔄 {Path.GetFileName(filePath)}: 结构与已有表一致，合并到 {targetTableName}");
            }
            // 8.4 结构不同：使用文件名作为表名
            else
            {
                // 生成基于文件名的表名
                var fileBasedTableName = GenerateTableNameFromFileName(fileName, baseTableName!);
    
                // 检查是否已存在该表名
                if (usedTableNames.Contains(fileBasedTableName))
                {
                    // 如果表名已存在，添加后缀
                    int suffix = 1;
                    string newTableName;
                    do
                    {
                        newTableName = $"{fileBasedTableName}_{suffix}";
                        suffix++;
                    } while (usedTableNames.Contains(newTableName));
                    fileBasedTableName = newTableName;
                }
    
                targetTableName = fileBasedTableName;
    
                // 记录新结构和表名
                structureSignatureMap[structureSignature] = targetTableName;
                tableStructureMap[targetTableName] = columns;
                usedTableNames.Add(targetTableName);
    
                importResults.Add($"📝 {Path.GetFileName(filePath)}: 使用独立表名 {targetTableName} ({columnCount} 列)");
            }

            // 9. 执行导入
            // 创建表（如果不存在）
            await _databaseService.CreateTableAsync(targetTableName, columns);

            // 插入数据
            var rows = data.Skip(1).ToList();
            await _databaseService.InsertDataAsync(targetTableName, columns, rows);

            totalImportedRows += rows.Count;
            importedTables.Add(targetTableName);
        }

        // 10. 显示导入结果
        await ThreadingHelper.RunOnUIThreadAsync(() =>
        {
            if (_disposed || _isCleaned) return;

            var message = $"✅ 导入完成!\n\n" +
                         $"📁 文件数: {filesToImport.Count}\n" +
                         $"📝 表数: {importedTables.Distinct().Count()}\n" +
                         $"📊 总行数: {totalImportedRows}\n" +
                         $"🕐 导入时间: {DateTime.Now:yyyy-MM-dd HH:mm:ss}\n\n" +
                         $"详情:\n{string.Join("\n", importResults)}";

            ShowImportStats = true;
            ImportStatsText = message;
            SetStatus($"✅ 导入成功: {totalImportedRows} 行数据", new SolidColorBrush(Colors.Green));
            IsLoading = false;
            LoadingMessage = string.Empty;
        });
    }
    catch (Exception ex)
    {
        await ThreadingHelper.RunOnUIThreadAsync(async () =>
        {
            if (_disposed || _isCleaned) return;
            var errorMsg = $"导入失败: {ex.Message}";
            await ShowMessageBoxAsync(errorMsg);
            SetStatus($"❌ {errorMsg}", new SolidColorBrush(Colors.Red));
            IsLoading = false;
            LoadingMessage = string.Empty;
        });
    }
}
    
    /// <summary>
/// 获取所有需要导入的文件列表
/// </summary>
private List<string> GetFilesToImport()
{
    var filesToImport = new List<string>();
    if (SelectedFiles.Count > 1)
    {
        var firstDir = Path.GetDirectoryName(FilePath);
        filesToImport.Add(FilePath);
        foreach (var fileName in SelectedFiles.Skip(1))
        {
            var fullPath = Path.Combine(firstDir ?? "", fileName);
            if (File.Exists(fullPath))
                filesToImport.Add(fullPath);
        }
    }
    else
    {
        filesToImport.Add(FilePath);
    }
    return filesToImport;
}
    
/// <summary>
/// 提取列名
/// </summary>
private List<string> ExtractColumns(List<List<object>> data)
{
    if (data == null || data.Count == 0 || data[0] == null)
        return new List<string>();

    var columns = new List<string>();
    foreach (var col in data[0])
    {
        var colName = col?.ToString()?.Trim() ?? $"Column{columns.Count + 1}";
        colName = SanitizeColumnName(colName);
        columns.Add(colName);
    }

    // 检查是否有空列名
    if (columns.Any(string.IsNullOrEmpty))
        return new List<string>();

    // 处理 Id 列冲突
    for (int i = 0; i < columns.Count; i++)
    {
        if (columns[i].Equals("Id", StringComparison.OrdinalIgnoreCase))
            columns[i] = "Id_Data";
    }

    return columns;
}

/// <summary>
/// 生成结构签名（用于比较表结构）
/// </summary>
private string GenerateStructureSignature(List<string> columns)
{
    if (columns == null || columns.Count == 0)
        return string.Empty;
    
    // 按列名排序并拼接，确保相同列集合产生相同签名
    var sortedColumns = columns.Select(c => c.ToLowerInvariant()).OrderBy(c => c);
    return string.Join("|", sortedColumns);
}

/// <summary>
/// 比较两列是否相等
/// </summary>
private bool AreColumnsEqual(List<string> columns1, List<string> columns2)
{
    if (columns1 == null && columns2 == null) return true;
    if (columns1 == null || columns2 == null) return false;
    if (columns1.Count != columns2.Count) return false;
    
    // 忽略大小写比较
    for (int i = 0; i < columns1.Count; i++)
    {
        if (!string.Equals(columns1[i], columns2[i], StringComparison.OrdinalIgnoreCase))
            return false;
    }
    return true;
}

/// <summary>
/// 从文件名生成表名（不使用 ref 参数）
/// </summary>
private string GenerateTableNameFromFileName(string fileName, string baseTableName)
{
    if (string.IsNullOrEmpty(fileName))
        return $"{baseTableName}_File";

    // 1. 清理文件名（替换非法字符为下划线）
    var cleanName = fileName
        .Replace(" ", "_")
        .Replace("-", "_")
        .Replace("/", "_")
        .Replace("\\", "_")
        .Replace(":", "_")
        .Replace("*", "_")
        .Replace("?", "_")
        .Replace("\"", "_")
        .Replace("<", "_")
        .Replace(">", "_")
        .Replace("|", "_")
        .Replace("'", "_")
        .Replace(";", "_")
        .Replace("(", "_")
        .Replace(")", "_")
        .Replace("[", "_")
        .Replace("]", "_")
        .Replace("{", "_")
        .Replace("}", "_")
        .Replace("+", "_")
        .Replace("=", "_")
        .Replace("&", "_")
        .Replace("%", "_")
        .Replace("#", "_")
        .Replace("@", "_")
        .Replace("!", "_")
        .Replace("$", "_")
        .Replace("`", "_")
        .Replace("~", "_")
        .Replace("^", "_");

    // 2. 合并多个下划线
    while (cleanName.Contains("__"))
        cleanName = cleanName.Replace("__", "_");

    // 3. 去除首尾下划线
    cleanName = cleanName.Trim('_');

    // 4. 如果为空，使用默认名称
    if (string.IsNullOrEmpty(cleanName))
        return $"{baseTableName}_File";

    // 5. 如果以数字开头，添加 T_ 前缀
    if (char.IsDigit(cleanName[0]))
        return $"T_{cleanName}";

    // 6. 如果包含非字母数字字符，添加 T_ 前缀
    if (cleanName.Any(c => !char.IsLetterOrDigit(c) && c != '_'))
        return $"T_{cleanName}";

    // 7. 如果是 SQL 关键字，添加 T_ 前缀
    var keywords = new[] { "SELECT", "INSERT", "UPDATE", "DELETE", "DROP", "CREATE", "ALTER", "TABLE", "FROM", "WHERE", 
                           "JOIN", "GROUP", "ORDER", "HAVING", "UNION", "INTERSECT", "EXCEPT", "WITH", "VIEW", "INDEX",
                           "PRIMARY", "FOREIGN", "KEY", "UNIQUE", "CHECK", "DEFAULT", "NULL", "NOT", "AND", "OR", "IN",
                           "LIKE", "BETWEEN", "IS", "EXISTS", "ANY", "ALL", "SOME" };
    if (keywords.Contains(cleanName.ToUpperInvariant()))
        return $"T_{cleanName}";

    // 8. 检查长度限制
    if (cleanName.Length > 60)
        cleanName = cleanName.Substring(0, 60);

    return cleanName;
}
    

    #endregion

    #region 辅助方法

    private static string SanitizeColumnName(string colName)
    {
        if (string.IsNullOrEmpty(colName))
            return "Column";

        var result = colName
            .Replace("、", "")
            .Replace("（", "")
            .Replace("）", "")
            .Replace("【", "")
            .Replace("】", "")
            .Replace("《", "")
            .Replace("》", "")
            .Replace("，", "")
            .Replace("。", "")
            .Replace("；", "")
            .Replace("：", "")
            .Replace("？", "")
            .Replace("！", "")
            .Replace("…", "")
            .Replace("·", "")
            .Replace("'", "")
            .Replace("\"", "")
            .Replace("/", "_")
            .Replace("\\", "_")
            .Replace("(", "")
            .Replace(")", "")
            .Replace("[", "")
            .Replace("]", "")
            .Replace("<", "")
            .Replace(">", "")
            .Replace("*", "")
            .Replace("?", "")
            .Replace(":", "_")
            .Replace("#", "")
            .Replace("%", "")
            .Replace("&", "_")
            .Replace("+", "_")
            .Replace("=", "_")
            .Replace("|", "_")
            .Trim();

        if (result.Length > 0 && char.IsDigit(result[0]))
        {
            result = "C" + result;
        }

        return string.IsNullOrEmpty(result) ? "Column" : result;
    }

    private void Clear()
    {
        if (_disposed || _isCleaned) return;

        _ = ThreadingHelper.RunOnUIThreadAsync(() =>
        {
            if (_disposed || _isCleaned) return;
            FilePath = string.Empty;
            TableName = string.Empty;
            TableNameInfo = string.Empty;
            TableNameValidation = string.Empty;
            ShowValidation = false;
            _currentFileName = null;
            _isAutoGenerated = false;
            SelectedFiles?.Clear();
            CanImport = false;
            UseDictionary = false;
            FileCount = 0;
            TotalRows = 0;
            ColumnCount = 0;
            ShowImportStats = false;
            ImportStatsText = string.Empty;
            IsLoading = false;
            LoadingMessage = string.Empty;
            
            if (SelectedBatch != null)
            {
                BatchInfo = $"已选批次: {SelectedBatch.Name}";
            }
            
            SetStatus(string.Empty, new SolidColorBrush(Colors.Transparent));
            ShowStatus = false;
        });
    }

    private void SetStatus(string message, IBrush color)
    {
        if (!Dispatcher.UIThread.CheckAccess())
        {
            Dispatcher.UIThread.Post(() => SetStatus(message, color));
            return;
        }

        StatusMessage = message;
        StatusColor = color;
        ShowStatus = !string.IsNullOrEmpty(message);
    }

    private void SetStatusSafe(string message, IBrush color)
    {
        _ = ThreadingHelper.RunOnUIThreadAsync(() =>
        {
            SetStatus(message, color);
        });
    }

    private async Task SetStatusAsync(string message, IBrush color)
    {
        await ThreadingHelper.RunOnUIThreadAsync(() =>
        {
            SetStatus(message, color);
        });
    }

    #endregion

    #region 对话框

    private Window? GetWindow()
    {
        if (_parentWindow != null)
            return _parentWindow;

        if (App.Current?.ApplicationLifetime is Avalonia.Controls.ApplicationLifetimes.IClassicDesktopStyleApplicationLifetime desktop)
        {
            return desktop.MainWindow ?? desktop.Windows.FirstOrDefault();
        }

        return null;
    }

    private async Task ShowMessageBoxAsync(string message)
    {
        if (_disposed || _isCleaned) return;

        var window = GetWindow();
        if (window == null) return;

        await ThreadingHelper.RunOnUIThreadAsync(async () =>
        {
            if (_disposed || _isCleaned || !window.IsVisible) return;

            var dialog = new Window
            {
                Title = "提示",
                Width = 500,
                Height = 300,
                WindowStartupLocation = WindowStartupLocation.CenterOwner
            };

            var button = new Button
            {
                Content = "确定",
                Width = 80,
                HorizontalAlignment = Avalonia.Layout.HorizontalAlignment.Center,
                Classes = { "PrimaryButton" }
            };

            button.Click += (sender, e) => dialog.Close();

            var textBlock = new TextBlock
            {
                Text = message,
                TextWrapping = Avalonia.Media.TextWrapping.Wrap,
                VerticalAlignment = Avalonia.Layout.VerticalAlignment.Center,
                HorizontalAlignment = Avalonia.Layout.HorizontalAlignment.Left
            };

            dialog.Content = new StackPanel
            {
                Margin = new Avalonia.Thickness(20),
                Spacing = 15,
                Children =
                {
                    textBlock,
                    button
                }
            };

            await dialog.ShowDialog(window);
        });
    }

    private async Task<bool> ShowConfirmDialogAsync(string message)
    {
        if (_disposed || _isCleaned) return false;

        var window = GetWindow();
        if (window == null) return false;

        return await ThreadingHelper.RunOnUIThreadAsync(async () =>
        {
            if (_disposed || _isCleaned || !window.IsVisible) return false;

            var tcs = new TaskCompletionSource<bool>();
            
            var dialog = new Window
            {
                Title = "确认导入",
                Width = 550,
                Height = 380,
                WindowStartupLocation = WindowStartupLocation.CenterOwner
            };

            var textBlock = new TextBlock 
            { 
                Text = message, 
                TextWrapping = Avalonia.Media.TextWrapping.Wrap,
                Margin = new Avalonia.Thickness(0, 0, 0, 10),
                FontSize = 13
            };

            var buttonPanel = new StackPanel
            {
                Orientation = Avalonia.Layout.Orientation.Horizontal,
                Spacing = 10,
                HorizontalAlignment = Avalonia.Layout.HorizontalAlignment.Center
            };

            var confirmButton = new Button 
            { 
                Content = "✅ 确认导入", 
                Width = 120,
                Classes = { "PrimaryButton" }
            };
            confirmButton.Click += (s, e) => 
            {
                tcs.SetResult(true);
                dialog.Close();
            };

            var cancelButton = new Button 
            { 
                Content = "❌ 取消", 
                Width = 100,
                Classes = { "DangerButton" }
            };
            cancelButton.Click += (s, e) => 
            {
                tcs.SetResult(false);
                dialog.Close();
            };

            buttonPanel.Children.Add(confirmButton);
            buttonPanel.Children.Add(cancelButton);
            
            dialog.Content = new StackPanel
            {
                Margin = new Avalonia.Thickness(20),
                Spacing = 15,
                Children =
                {
                    textBlock,
                    buttonPanel
                }
            };

            await dialog.ShowDialog(window);
            return await tcs.Task;
        });
    }

    #endregion

    #region ICleanupPage 实现

    public void Cleanup()
    {
        if (_isCleaned) return;

        try
        {
            CancelCurrentOperation();

            _lock.Wait(TimeSpan.FromSeconds(2));
            try
            {
                _subscriptions?.Dispose();

                _ = ThreadingHelper.RunOnUIThreadAsync(() =>
                {
                    try
                    {
                        Batches?.Clear();
                        DataDictionaries?.Clear();
                        SelectedFiles?.Clear();
                        SelectedBatch = null;
                        SelectedDictionary = null;
                        StatusMessage = string.Empty;
                        ShowStatus = false;
                        FilePath = string.Empty;
                        TableName = string.Empty;
                        TableNameInfo = string.Empty;
                        TableNameValidation = string.Empty;
                        ShowValidation = false;
                        _currentFileName = null;
                        _isAutoGenerated = false;
                        CanImport = false;
                        UseDictionary = false;
                        IsLoading = false;
                        LoadingMessage = string.Empty;
                        ShowImportStats = false;
                        ImportStatsText = string.Empty;
                        FileCount = 0;
                        TotalRows = 0;
                        ColumnCount = 0;
                    }
                    catch { }
                });

                _isCleaned = true;
            }
            finally
            {
                try { _lock.Release(); } catch { }
            }
        }
        catch
        {
            _isCleaned = true;
        }
    }

    #endregion

    #region IDisposable 实现

    public void Dispose()
    {
        if (_disposed) return;

        try
        {
            Cleanup();
            _lock?.Dispose();
            _cts?.Dispose();
            _cts = null;
            _disposed = true;
        }
        catch
        {
            _disposed = true;
        }

        GC.SuppressFinalize(this);
    }

    #endregion
}