using Avalonia.Controls;
using Avalonia.Media;
using Avalonia.Threading;
using ExcelToSQLite.Models;
using ExcelToSQLite.Services;
using ReactiveUI;
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.IO;
using System.Linq;
using System.Reactive;
using System.Reactive.Disposables;
using System.Reactive.Linq;
using System.Threading;
using System.Threading.Tasks;
using ExcelToSQLite.Helpers;

namespace ExcelToSQLite.ViewModels
{
    /// <summary>
    /// 加油卡数据导入 ViewModel - 实现 ICleanupPage 和 IDisposable 以确保资源正确释放
    /// </summary>
    public class FuelCardViewModel : ReactiveObject, ICleanupPage, IDisposable
    {
        private readonly FuelCardParserService? _parserService;
        private readonly DatabaseService? _databaseService;
        private readonly AnalysisBatchService? _batchService;
        private readonly DataDictionaryService? _dictionaryService;
        private readonly SemaphoreSlim _lock = new SemaphoreSlim(1, 1);
        private readonly CompositeDisposable _subscriptions = new CompositeDisposable();
        private CancellationTokenSource? _cts;
        
        private Window? _parentWindow;
        private bool _disposed;
        private bool _isCleaned;
        private bool _isLoading;
        private string _loadingMessage = string.Empty;
        
        // 文件相关
        private string _filePath = string.Empty;
        private ObservableCollection<string> _selectedFiles = new();
        private int _fileCount;
        private string? _lastOpenDirectory;
        
        // 表名相关
        private string _tableName = string.Empty;
        private string _tableNameInfo = string.Empty;
        private string _tableNameValidation = string.Empty;
        private IBrush _validationColor = new SolidColorBrush(Colors.Green);
        private bool _showValidation = false;
        private bool _isAutoGenerated = false;
        private string? _currentFileName;
        
        // 状态
        private bool _canImport;
        private string _statusMessage = string.Empty;
        private IBrush _statusColor = new SolidColorBrush(Colors.Transparent);
        private bool _showStatus = false;
        private bool _showImportStats;
        private string _importStatsText = string.Empty;
        
        // 数据统计
        private int _totalRecords = 0;
        private int _cardCount = 0;
        private decimal _totalAmount = 0;
        private decimal _totalFuelVolume = 0;
        private string _totalAmountDisplay = "0.00";
        private int _fuelRecordCount = 0;
        private int _depositRecordCount = 0;
        
        // 批次
        private ObservableCollection<AnalysisBatch> _batches = new();
        private AnalysisBatch? _selectedBatch;
        private string _batchInfo = string.Empty;

        // 数据字典
        private ObservableCollection<DataDictionary> _dataDictionaries = new();
        private DataDictionary? _selectedDictionary;
        private string _dictionaryInfo = string.Empty;
        private bool _useDictionary = false;

        // 解析后的记录
        private List<FuelCardRecord> _allRecords = new();
        
        public ReactiveCommand<Unit, Unit>? DownloadTemplateCommand { get; private set; }

        public FuelCardViewModel()
        {
            try
            {
                _parserService = new FuelCardParserService();
                _databaseService = DatabaseService.Instance;
                _batchService = new AnalysisBatchService();
                _dictionaryService = new DataDictionaryService();
                
                SelectFileCommand = ReactiveCommand.CreateFromTask(SelectFileAsync);
                ImportCommand = ReactiveCommand.CreateFromTask(ImportAsync, this.WhenAnyValue(x => x.CanImport));
                ClearCommand = ReactiveCommand.Create(Clear);
                RefreshBatchesCommand = ReactiveCommand.CreateFromTask(LoadBatchesAsync);
                RefreshDictionariesCommand = ReactiveCommand.CreateFromTask(LoadDictionariesAsync);
                GenerateTableNameCommand = ReactiveCommand.Create(GenerateTableName);
                
                // 订阅命令异常
                SelectFileCommand.ThrownExceptions
                    .ObserveOn(RxApp.MainThreadScheduler)
                    .Subscribe(ex =>
                    {
                        SetStatus($"选择文件失败: {ex.Message}", new SolidColorBrush(Colors.Red));
                    })
                    .DisposeWith(_subscriptions);

                ImportCommand.ThrownExceptions
                    .ObserveOn(RxApp.MainThreadScheduler)
                    .Subscribe(ex =>
                    {
                        SetStatus($"导入失败: {ex.Message}", new SolidColorBrush(Colors.Red));
                    })
                    .DisposeWith(_subscriptions);
                
                CanImport = false;
                
                // 监听表名变化
                this.WhenAnyValue(x => x.TableName)
                    .Subscribe(_ => ValidateTableName())
                    .DisposeWith(_subscriptions);
                
                // 监听数据字典选择变化
                this.WhenAnyValue(x => x.SelectedDictionary)
                    .Subscribe(_ => 
                    {
                        if (UseDictionary && SelectedDictionary != null && !string.IsNullOrEmpty(_currentFileName))
                        {
                            GenerateTableName();
                        }
                    })
                    .DisposeWith(_subscriptions);
                
                // 监听是否使用数据字典
                this.WhenAnyValue(x => x.UseDictionary)
                    .Subscribe(_ => 
                    {
                        if (UseDictionary && SelectedDictionary != null && !string.IsNullOrEmpty(_currentFileName))
                        {
                            GenerateTableName();
                        }
                        else if (!UseDictionary && !string.IsNullOrEmpty(_currentFileName))
                        {
                            GenerateTableName();
                        }
                    })
                    .DisposeWith(_subscriptions);
                
                // 添加下载模板命令
                DownloadTemplateCommand = ReactiveCommand.CreateFromTask(DownloadTemplateAsync);
                DownloadTemplateCommand.ThrownExceptions
                    .ObserveOn(RxApp.MainThreadScheduler)
                    .Subscribe(ex =>
                    {
                        SetStatus($"下载模板失败: {ex.Message}", new SolidColorBrush(Colors.Red));
                    })
                    .DisposeWith(_subscriptions);
                
                // 启动异步初始化
                _ = InitializeAsync();
            }
            catch (Exception ex)
            {
                SetStatusSafe($"初始化失败: {ex.Message}", new SolidColorBrush(Colors.Red));
            }
        }
        
        #region 下载模板

        private async Task DownloadTemplateAsync()
        {
            if (_disposed || _isCleaned) return;
            
            try
            {
                string templateFileName = "Resources/Templates/中国石化加油IC卡台帐对帐单.xlsx";
                string templatePath = Path.Combine(AppContext.BaseDirectory, templateFileName);
                
                if (!File.Exists(templatePath))
                {
                    string sourcePath = Path.Combine(AppContext.BaseDirectory, "..", "..", "..", "Resources", "Templates", "中国石化加油IC卡台帐对帐单.xlsx");
                    if (File.Exists(sourcePath))
                    {
                        string? targetDir = Path.GetDirectoryName(templatePath);
                        if (!string.IsNullOrEmpty(targetDir) && !Directory.Exists(targetDir))
                            Directory.CreateDirectory(targetDir);
                        
                        File.Copy(sourcePath, templatePath, true);
                    }
                    else
                    {
                        await ShowErrorMessageAsync("未找到模板文件: 中国石化加油IC卡台帐对帐单.xlsx\n\n请确保文件已添加到 Resources/Templates/ 目录", "文件未找到");
                        return;
                    }
                }
                
                var window = GetWindow();
                if (window == null)
                {
                    await ShowErrorMessageAsync("无法获取窗口句柄", "错误");
                    return;
                }
                
                var storageProvider = window.StorageProvider;
                if (storageProvider == null)
                {
                    await ShowErrorMessageAsync("无法获取文件存储服务", "错误");
                    return;
                }
                
                var options = new Avalonia.Platform.Storage.FilePickerSaveOptions
                {
                    Title = "保存加油卡样表模板",
                    SuggestedFileName = "中国石化加油IC卡台帐对帐单.xlsx",
                    FileTypeChoices = new List<Avalonia.Platform.Storage.FilePickerFileType>
                    {
                        new("Excel 文件 (*.xlsx)") { Patterns = new List<string> { "*.xlsx" } }
                    },
                    DefaultExtension = ".xlsx"
                };
                
                var file = await storageProvider.SaveFilePickerAsync(options);
                if (file == null)
                {
                    return;
                }
                
                var savePath = file.Path?.LocalPath ?? file.Name;
                if (string.IsNullOrEmpty(savePath))
                {
                    await ShowErrorMessageAsync("获取保存路径失败", "错误");
                    return;
                }
                
                string? saveDir = Path.GetDirectoryName(savePath);
                if (!string.IsNullOrEmpty(saveDir) && !Directory.Exists(saveDir))
                    Directory.CreateDirectory(saveDir);
                
                File.Copy(templatePath, savePath, true);
                
                SetStatus($"✅ 模板已保存到: {Path.GetFileName(savePath)}", new SolidColorBrush(Colors.Green));
                
                var openFolder = await ShowConfirmDialogAsync($"模板已保存成功！\n\n是否打开文件所在文件夹？", "保存成功");
                if (openFolder)
                {
                    System.Diagnostics.Process.Start("explorer.exe", $"/select,\"{savePath}\"");
                }
            }
            catch (Exception ex)
            {
                await ShowErrorMessageAsync($"下载模板失败: {ex.Message}", "下载失败");
                SetStatus($"❌ 下载失败: {ex.Message}", new SolidColorBrush(Colors.Red));
            }
        }

        #endregion

        #region 公共方法

        public void SetParentWindow(Window window)
        {
            _parentWindow = window;
        }

        #endregion

        #region 属性

        public bool IsLoading
        {
            get => _isLoading;
            set => this.RaiseAndSetIfChanged(ref _isLoading, value);
        }

        public string LoadingMessage
        {
            get => _loadingMessage;
            set => this.RaiseAndSetIfChanged(ref _loadingMessage, value);
        }

        public string FilePath
        {
            get => _filePath;
            set => this.RaiseAndSetIfChanged(ref _filePath, value);
        }

        public ObservableCollection<string> SelectedFiles
        {
            get => _selectedFiles;
            set => this.RaiseAndSetIfChanged(ref _selectedFiles, value);
        }

        public int FileCount
        {
            get => _fileCount;
            set => this.RaiseAndSetIfChanged(ref _fileCount, value);
        }

        public string TableName
        {
            get => _tableName;
            set
            {
                this.RaiseAndSetIfChanged(ref _tableName, value);
                if (!string.IsNullOrEmpty(value))
                {
                    _isAutoGenerated = false;
                }
            }
        }

        public string TableNameInfo
        {
            get => _tableNameInfo;
            set => this.RaiseAndSetIfChanged(ref _tableNameInfo, value);
        }

        public string TableNameValidation
        {
            get => _tableNameValidation;
            set => this.RaiseAndSetIfChanged(ref _tableNameValidation, value);
        }

        public IBrush ValidationColor
        {
            get => _validationColor;
            set => this.RaiseAndSetIfChanged(ref _validationColor, value);
        }

        public bool ShowValidation
        {
            get => _showValidation;
            set => this.RaiseAndSetIfChanged(ref _showValidation, value);
        }

        public bool CanImport
        {
            get => _canImport;
            set => this.RaiseAndSetIfChanged(ref _canImport, value);
        }

        public string StatusMessage
        {
            get => _statusMessage;
            set => this.RaiseAndSetIfChanged(ref _statusMessage, value);
        }

        public IBrush StatusColor
        {
            get => _statusColor;
            set => this.RaiseAndSetIfChanged(ref _statusColor, value);
        }

        public bool ShowStatus
        {
            get => _showStatus;
            set => this.RaiseAndSetIfChanged(ref _showStatus, value);
        }

        public bool ShowImportStats
        {
            get => _showImportStats;
            set => this.RaiseAndSetIfChanged(ref _showImportStats, value);
        }

        public string ImportStatsText
        {
            get => _importStatsText;
            set => this.RaiseAndSetIfChanged(ref _importStatsText, value);
        }

        // 数据统计
        public int TotalRecords
        {
            get => _totalRecords;
            set => this.RaiseAndSetIfChanged(ref _totalRecords, value);
        }

        public int CardCount
        {
            get => _cardCount;
            set => this.RaiseAndSetIfChanged(ref _cardCount, value);
        }

        public decimal TotalAmount
        {
            get => _totalAmount;
            set => this.RaiseAndSetIfChanged(ref _totalAmount, value);
        }

        public decimal TotalFuelVolume
        {
            get => _totalFuelVolume;
            set => this.RaiseAndSetIfChanged(ref _totalFuelVolume, value);
        }

        public string TotalAmountDisplay
        {
            get => _totalAmountDisplay;
            set => this.RaiseAndSetIfChanged(ref _totalAmountDisplay, value);
        }

        public int FuelRecordCount
        {
            get => _fuelRecordCount;
            set => this.RaiseAndSetIfChanged(ref _fuelRecordCount, value);
        }

        public int DepositRecordCount
        {
            get => _depositRecordCount;
            set => this.RaiseAndSetIfChanged(ref _depositRecordCount, value);
        }

        // 批次
        public ObservableCollection<AnalysisBatch> Batches
        {
            get => _batches;
            set => this.RaiseAndSetIfChanged(ref _batches, value);
        }

        public AnalysisBatch? SelectedBatch
        {
            get => _selectedBatch;
            set
            {
                this.RaiseAndSetIfChanged(ref _selectedBatch, value);
                if (value != null)
                {
                    var createdTime = value.CreatedAt.ToString("yyyy-MM-dd HH:mm");
                    BatchInfo = $"已选批次: {value.Name} (创建: {createdTime})";
                    if (!string.IsNullOrEmpty(_currentFileName))
                    {
                        GenerateTableName();
                    }
                }
                else
                {
                    BatchInfo = "请选择批次";
                }
            }
        }

        public string BatchInfo
        {
            get => _batchInfo;
            set => this.RaiseAndSetIfChanged(ref _batchInfo, value);
        }

        // 数据字典
        public ObservableCollection<DataDictionary> DataDictionaries
        {
            get => _dataDictionaries;
            set => this.RaiseAndSetIfChanged(ref _dataDictionaries, value);
        }

        public DataDictionary? SelectedDictionary
        {
            get => _selectedDictionary;
            set
            {
                this.RaiseAndSetIfChanged(ref _selectedDictionary, value);
                if (value != null)
                {
                    DictionaryInfo = $"已选字典: {value.Name} (表名: {(string.IsNullOrEmpty(value.TableName) ? "使用文件名" : value.TableName)})";
                    if (UseDictionary && !string.IsNullOrEmpty(_currentFileName))
                    {
                        GenerateTableName();
                    }
                }
                else
                {
                    DictionaryInfo = "未选择数据字典";
                }
            }
        }

        public string DictionaryInfo
        {
            get => _dictionaryInfo;
            set => this.RaiseAndSetIfChanged(ref _dictionaryInfo, value);
        }

        public bool UseDictionary
        {
            get => _useDictionary;
            set
            {
                this.RaiseAndSetIfChanged(ref _useDictionary, value);
                if (!string.IsNullOrEmpty(_currentFileName))
                {
                    GenerateTableName();
                }
            }
        }

        #endregion

        #region 命令

        public ReactiveCommand<Unit, Unit> SelectFileCommand { get; } = null!;
        public ReactiveCommand<Unit, Unit> ImportCommand { get; } = null!;
        public ReactiveCommand<Unit, Unit> ClearCommand { get; } = null!;
        public ReactiveCommand<Unit, Unit> RefreshBatchesCommand { get; } = null!;
        public ReactiveCommand<Unit, Unit> RefreshDictionariesCommand { get; } = null!;
        public ReactiveCommand<Unit, Unit> GenerateTableNameCommand { get; } = null!;

        #endregion

        #region 初始化

        private async Task InitializeAsync()
        {
            if (_disposed || _isCleaned) return;

            await _lock.WaitAsync();
            try
            {
                if (_disposed || _isCleaned) return;

                _cts = new CancellationTokenSource();
                var token = _cts.Token;

                var loadBatchesTask = LoadBatchesAsync();
                var loadDictionariesTask = LoadDictionariesAsync();

                await Task.WhenAll(loadBatchesTask, loadDictionariesTask);

                if (!token.IsCancellationRequested && !_disposed && !_isCleaned)
                {
                    SetStatus("初始化完成", new SolidColorBrush(Colors.Green));
                }
            }
            catch (OperationCanceledException)
            {
            }
            catch (Exception ex)
            {
                await SetStatusAsync($"初始化失败: {ex.Message}", new SolidColorBrush(Colors.Red));
            }
            finally
            {
                _lock.Release();
            }
        }

        #endregion

        #region 数据加载

        private async Task LoadBatchesAsync()
        {
            if (_disposed || _isCleaned) return;
            if (_batchService == null) return;

            try
            {
                await ThreadingHelper.RunOnUIThreadAsync(() =>
                {
                    if (_disposed || _isCleaned) return;
                    IsLoading = true;
                    LoadingMessage = "正在加载批次...";
                    SetStatus("正在加载批次...", new SolidColorBrush(Colors.Orange));
                });

                var list = await _batchService.GetAllAsync(1000);
                var sortedList = list.OrderByDescending(b => b.CreatedAt).ToList();
                
                await ThreadingHelper.RunOnUIThreadAsync(() =>
                {
                    if (_disposed || _isCleaned) return;
                    Batches = new ObservableCollection<AnalysisBatch>(sortedList);

                    if (Batches.Count > 0)
                    {
                        SelectedBatch = Batches[0];
                        BatchInfo = $"共 {Batches.Count} 个批次，已选择最新的批次: {SelectedBatch.Name}";
                        if (!string.IsNullOrEmpty(_currentFileName))
                        {
                            GenerateTableName();
                        }
                    }
                    else
                    {
                        BatchInfo = "暂无批次，请先在批次管理页面创建";
                        SelectedBatch = null;
                    }
                    
                    IsLoading = false;
                    LoadingMessage = string.Empty;
                    SetStatus("批次加载完成", new SolidColorBrush(Colors.Green));
                });
            }
            catch (Exception ex)
            {
                await ThreadingHelper.RunOnUIThreadAsync(() =>
                {
                    if (_disposed || _isCleaned) return;
                    SetStatus($"加载批次失败: {ex.Message}", new SolidColorBrush(Colors.Red));
                    BatchInfo = "加载批次失败";
                    IsLoading = false;
                    LoadingMessage = string.Empty;
                });
            }
        }

        private async Task LoadDictionariesAsync()
        {
            if (_disposed || _isCleaned) return;
            if (_dictionaryService == null) return;

            try
            {
                await _dictionaryService.InitializeAsync();
                var list = await _dictionaryService.GetAllAsync();
                
                await ThreadingHelper.RunOnUIThreadAsync(() =>
                {
                    if (_disposed || _isCleaned) return;
                    DataDictionaries = new ObservableCollection<DataDictionary>(list);
                    
                    if (DataDictionaries.Count > 0)
                    {
                        SelectedDictionary = DataDictionaries[0];
                        DictionaryInfo = $"已加载 {DataDictionaries.Count} 个数据字典";
                    }
                    else
                    {
                        DictionaryInfo = "暂无数据字典，请先在数据字典页面创建";
                        SelectedDictionary = null;
                    }
                });
            }
            catch (Exception ex)
            {
                await ThreadingHelper.RunOnUIThreadAsync(() =>
                {
                    if (_disposed || _isCleaned) return;
                    SetStatus($"加载数据字典失败: {ex.Message}", new SolidColorBrush(Colors.Red));
                    DictionaryInfo = "加载数据字典失败";
                });
            }
        }

        #endregion

        #region 文件选择

        private async Task SelectFileAsync()
        {
            if (_disposed || _isCleaned) return;

            CancelCurrentOperation();

            try
            {
                var window = GetWindow();
                if (window == null)
                {
                    await ShowErrorMessageAsync("无法获取窗口句柄", "错误");
                    return;
                }

                var filePaths = await OpenMultipleExcelFilesAsync(window, "选择加油卡文件（可多选）");

                if (filePaths != null && filePaths.Count > 0)
                {
                    if (filePaths.Count > 0)
                    {
                        _lastOpenDirectory = Path.GetDirectoryName(filePaths[0]);
                    }

                    var primaryFilePath = filePaths[0];

                    await ThreadingHelper.RunOnUIThreadAsync(() =>
                    {
                        if (_disposed || _isCleaned) return;
                        FilePath = primaryFilePath;
                        _currentFileName = Path.GetFileNameWithoutExtension(primaryFilePath);
                        SelectedFiles = new ObservableCollection<string>(filePaths.Select(f => Path.GetFileName(f) ?? f));
                        FileCount = filePaths.Count;
                        GenerateTableName();
                    });

                    await ParseAllFilesAsync(filePaths);
                }
            }
            catch (OperationCanceledException)
            {
            }
            catch (Exception ex)
            {
                await ShowErrorMessageAsync($"选择文件失败: {ex.Message}", "错误");
            }
        }

        private async Task<List<string>?> OpenMultipleExcelFilesAsync(Window? parent, string title)
        {
            if (parent == null || !parent.IsVisible || parent.WindowState == WindowState.Minimized)
                return null;

            var storageProvider = parent.StorageProvider;
            if (storageProvider == null) return null;

            var options = new Avalonia.Platform.Storage.FilePickerOpenOptions
            {
                Title = title,
                AllowMultiple = true,
                SuggestedStartLocation = !string.IsNullOrEmpty(_lastOpenDirectory) 
                    ? await storageProvider.TryGetFolderFromPathAsync(new Uri(_lastOpenDirectory))
                    : null,
                FileTypeFilter = new List<Avalonia.Platform.Storage.FilePickerFileType>
                {
                    new("Excel 文件 (*.xlsx, *.xls)")
                    {
                        Patterns = new List<string> { "*.xlsx", "*.xls" }
                    },
                    new("所有文件 (*.*)")
                    {
                        Patterns = new List<string> { "*" }
                    }
                }
            };

            try
            {
                using var cts = new CancellationTokenSource(TimeSpan.FromSeconds(30));
                var files = await storageProvider.OpenFilePickerAsync(options).WaitAsync(cts.Token);
                if (files != null && files.Count > 0)
                {
                    return files.Select(f => f.Path?.LocalPath ?? f.Name).ToList();
                }
            }
            catch
            {
            }

            return null;
        }

        #endregion

        #region 文件解析

        private async Task ParseAllFilesAsync(List<string> filePaths)
        {
            if (_disposed || _isCleaned) return;
            if (_parserService == null) return;

            CancelCurrentOperation();

            try
            {
                await ThreadingHelper.RunOnUIThreadAsync(() =>
                {
                    if (_disposed || _isCleaned) return;
                    IsLoading = true;
                    LoadingMessage = "正在解析加油卡文件...";
                    SetStatus("正在解析加油卡文件...", new SolidColorBrush(Colors.Orange));
                });

                _cts = new CancellationTokenSource();
                var token = _cts.Token;

                var allRecords = new List<FuelCardRecord>();
                int processedFiles = 0;
                var fileResults = new List<string>();

                foreach (var filePath in filePaths)
                {
                    if (token.IsCancellationRequested || _disposed || _isCleaned) break;

                    var fileName = Path.GetFileName(filePath);
                    processedFiles++;

                    await ThreadingHelper.RunOnUIThreadAsync(() =>
                    {
                        LoadingMessage = $"正在解析: {fileName} ({processedFiles}/{filePaths.Count})";
                    });

                    try
                    {
                        var records = await _parserService.ParseFuelCardAsync(filePath);
                        var validRecords = records.Where(r => r.IsValidRecord).ToList();
                        
                        allRecords.AddRange(validRecords);
                        fileResults.Add($"✅ {fileName}: {validRecords.Count} 条记录");
                    }
                    catch (Exception ex)
                    {
                        fileResults.Add($"❌ {fileName}: {ex.Message}");
                    }
                }

                if (token.IsCancellationRequested || _disposed || _isCleaned) return;

                // 更新统计信息
                _allRecords = allRecords;
                TotalRecords = allRecords.Count;
                CardCount = allRecords.Select(r => r.CardNumber).Distinct().Count();
                TotalAmount = allRecords.Sum(r => r.Amount);
                TotalFuelVolume = allRecords.Sum(r => r.Quantity);
                TotalAmountDisplay = TotalAmount.ToString("N2");
                
                // 统计圈存和加油记录数量
                FuelRecordCount = allRecords.Count(r => r.BusinessType == "加油");
                DepositRecordCount = allRecords.Count(r => r.BusinessType == "圈存");

                await ThreadingHelper.RunOnUIThreadAsync(() =>
                {
                    if (_disposed || _isCleaned) return;
                    
                    GenerateTableName();
                    ValidateTableName();
                    CanImport = allRecords.Count > 0;
                    IsLoading = false;
                    LoadingMessage = string.Empty;
                    
                    var summary = $"✅ 解析完成！共 {allRecords.Count} 条记录，" +
                                  $"其中加油 {FuelRecordCount} 条，圈存 {DepositRecordCount} 条，" +
                                  $"{CardCount} 张卡，总金额 {TotalAmount:N2} 元";
                    SetStatus(summary, new SolidColorBrush(Colors.Green));
                    
                    // 如果有错误，显示警告
                    if (fileResults.Any(r => r.Contains("❌")))
                    {
                        var errors = string.Join("\n", fileResults.Where(r => r.Contains("❌")));
                        _ = ShowWarningMessageAsync($"部分文件解析失败:\n{errors}", "解析警告");
                    }
                });
            }
            catch (OperationCanceledException)
            {
                await ThreadingHelper.RunOnUIThreadAsync(() =>
                {
                    if (!_disposed && !_isCleaned)
                    {
                        IsLoading = false;
                        LoadingMessage = string.Empty;
                        SetStatus("解析已取消", new SolidColorBrush(Colors.Orange));
                    }
                });
            }
            catch (Exception ex)
            {
                await ThreadingHelper.RunOnUIThreadAsync(async () =>
                {
                    if (_disposed || _isCleaned) return;
                    await ShowErrorMessageAsync($"解析失败: {ex.Message}", "解析失败");
                    SetStatus($"❌ 解析失败: {ex.Message}", new SolidColorBrush(Colors.Red));
                    CanImport = false;
                    IsLoading = false;
                    LoadingMessage = string.Empty;
                });
            }
        }

        #endregion

        #region 表名生成

        private void GenerateTableName()
        {
            if (_disposed || _isCleaned) return;

            if (string.IsNullOrEmpty(FilePath) || SelectedBatch == null)
            {
                TableName = string.Empty;
                TableNameInfo = "请选择文件和批次后自动生成表名";
                return;
            }

            var fileName = Path.GetFileNameWithoutExtension(FilePath);
            var tablePrefix = SelectedBatch.TablePrefix;
            string generatedName;

            if (UseDictionary && SelectedDictionary != null)
            {
                generatedName = PublicEvent.GetFormatFilename(tablePrefix, fileName, SelectedDictionary.TableName);
            }
            else
            {
                generatedName = PublicEvent.GetFormatFilename(tablePrefix, fileName);
            }

            TableName = generatedName;
            _isAutoGenerated = true;
            ValidateTableName();
        }

        private void ValidateTableName()
        {
            if (_disposed || _isCleaned) return;

            if (string.IsNullOrEmpty(TableName))
            {
                TableNameValidation = "⚠️ 表名不能为空";
                ValidationColor = new SolidColorBrush(Colors.Orange);
                ShowValidation = true;
                return;
            }

            var invalidChars = new[] { ' ', '-', '/', '\\', ':', '*', '?', '"', '<', '>', '|', '\'', ';' };
            if (TableName.IndexOfAny(invalidChars) >= 0)
            {
                TableNameValidation = "❌ 表名包含非法字符，请使用字母、数字和下划线";
                ValidationColor = new SolidColorBrush(Colors.Red);
                ShowValidation = true;
                return;
            }

            if (!char.IsLetter(TableName[0]))
            {
                TableNameValidation = "⚠️ 表名应以字母开头";
                ValidationColor = new SolidColorBrush(Colors.Orange);
                ShowValidation = true;
                return;
            }

            if (TableName.Length > 60)
            {
                TableNameValidation = $"⚠️ 表名过长 ({TableName.Length}/60)，建议缩短";
                ValidationColor = new SolidColorBrush(Colors.Orange);
                ShowValidation = true;
                return;
            }

            if (_isAutoGenerated)
            {
                TableNameValidation = "✅ 表名有效 (自动生成)";
            }
            else
            {
                TableNameValidation = "✅ 表名有效 (已自定义)";
            }
            ValidationColor = new SolidColorBrush(Colors.Green);
            ShowValidation = true;
        }

        #endregion

        #region 取消操作

        private void CancelCurrentOperation()
        {
            try
            {
                _cts?.Cancel();
                _cts?.Dispose();
                _cts = null;
            }
            catch
            {
            }
        }

        #endregion

        #region 导入
        
        private async Task ImportAsync()
{
    if (_disposed || _isCleaned) return;
    if (IsLoading) return;
    if (_databaseService == null) return;

    try
    {
        if (string.IsNullOrEmpty(FilePath))
        {
            await ShowWarningMessageAsync("请先选择Excel文件", "提示");
            return;
        }

        if (SelectedBatch == null)
        {
            await ShowWarningMessageAsync("请先选择分析批次", "提示");
            return;
        }

        if (string.IsNullOrEmpty(TableName))
        {
            await ShowWarningMessageAsync("请输入表名或点击'自动生成'", "提示");
            return;
        }

        if (TableName.IndexOfAny(new[] { ' ', '-', '/', '\\', ':', '*', '?', '"', '<', '>', '|', '\'', ';' }) >= 0)
        {
            await ShowWarningMessageAsync("表名包含非法字符，请使用字母、数字和下划线", "提示");
            return;
        }

        if (!char.IsLetter(TableName[0]))
        {
            await ShowWarningMessageAsync("表名应以字母开头", "提示");
            return;
        }

        if (_allRecords.Count == 0)
        {
            await ShowWarningMessageAsync("没有可导入的数据", "提示");
            return;
        }

        // 创建 FuelCardTableService 实例
        var fuelCardTableService = new FuelCardTableService();

        // 检查表是否存在并获取实际表名
        var tableExists = await fuelCardTableService.TableExistsAsync(TableName);
        string actualTableName = TableName;

        // 如果表已存在，检查结构
        if (tableExists)
        {
            // 验证表结构
            var isValid = await fuelCardTableService.ValidateTableStructureAsync(TableName);
            if (!isValid)
            {
                // 表结构不匹配，自动生成新表名
                var newTableName = await fuelCardTableService.GenerateAvailableTableNameAsync(TableName);
                
                // 提示用户表名已变更
                var confirmUseNewName = await ShowConfirmDialogAsync(
                    $"⚠️ 表 '{TableName}' 已存在但结构不匹配。\n\n" +
                    $"将使用新表名: '{newTableName}'\n\n" +
                    $"是否继续导入？",
                    "表名已变更"
                );
                
                if (!confirmUseNewName) return;
                
                actualTableName = newTableName;
                tableExists = false; // 新表不存在
                
                // 更新界面上的表名
                await ThreadingHelper.RunOnUIThreadAsync(() =>
                {
                    TableName = actualTableName;
                    TableNameValidation = $"✅ 已自动生成新表名: {actualTableName}";
                    ValidationColor = new SolidColorBrush(Colors.Green);
                });
            }
        }
        
        // 构建确认消息
        string confirmMessage = $"📊 确认导入加油卡记录\n\n" +
                               $"📁 文件数: {FileCount}\n" +
                               $"📋 批次: {SelectedBatch.Name}\n" +
                               $"📝 表名: {actualTableName}\n" +
                               $"{(tableExists ? "📌 数据将追加到现有表" : "📌 将创建新表")}\n" +
                               $"📊 总记录数: {TotalRecords}\n" +
                               $"⛽ 加油记录: {FuelRecordCount}\n" +
                               $"💰 圈存记录: {DepositRecordCount}\n" +
                               $"💳 卡数: {CardCount}\n" +
                               $"💰 总金额: {TotalAmount:N2}元\n" +
                               $"⛽ 总升数: {TotalFuelVolume:F2}L";

        if (UseDictionary && SelectedDictionary != null)
        {
            confirmMessage += $"\n📚 数据字典: {SelectedDictionary.Name}";
        }

        confirmMessage += $"\n\n确认继续导入？";

        var confirm = await ShowConfirmDialogAsync(confirmMessage, "确认导入");
        if (!confirm) return;

        await ThreadingHelper.RunOnUIThreadAsync(() =>
        {
            if (_disposed || _isCleaned) return;
            IsLoading = true;
            LoadingMessage = "正在准备导入...";
            SetStatus("正在导入数据...", new SolidColorBrush(Colors.Orange));
        });

        try
        {
            // 创建表（使用中文列名）- 如果表已存在且结构正确，不会重复创建
            var columns = new List<string>
            {
                "卡号",
                "交易时间",
                "业务类型",
                "油品类型",
                "数量",
                "单价",
                "金额",
                "奖励分值",
                "优惠价",
                "余额",
                "地点",
                "操作员",
                "备注",
                "客户名称",
                "网点名称"
            };

            // 使用 FuelCardTableService 创建表（会自动处理表名冲突）
            var finalTableName = await fuelCardTableService.CreateTableAsync(actualTableName, columns);
            
            // 如果最终表名与预期不同，更新记录
            if (finalTableName != actualTableName)
            {
                await ThreadingHelper.RunOnUIThreadAsync(() =>
                {
                    TableName = finalTableName;
                    TableNameValidation = $"✅ 已自动生成新表名: {finalTableName}";
                    ValidationColor = new SolidColorBrush(Colors.Green);
                });
                actualTableName = finalTableName;
            }

            // 分批插入数据
            int batchSize = 500;
            int totalBatches = (int)Math.Ceiling((double)_allRecords.Count / batchSize);
            int importedCount = 0;

            for (int batch = 0; batch < totalBatches; batch++)
            {
                if (_disposed || _isCleaned) break;

                var batchRecords = _allRecords.Skip(batch * batchSize).Take(batchSize).ToList();
                
                await ThreadingHelper.RunOnUIThreadAsync(() =>
                {
                    LoadingMessage = $"正在导入数据... ({batch + 1}/{totalBatches})";
                });

                // 使用 FuelCardTableService 插入数据
                var inserted = await fuelCardTableService.InsertRecordsAsync(actualTableName, batchRecords);
                importedCount += inserted;
            }

            await ThreadingHelper.RunOnUIThreadAsync(async () =>
            {
                if (_disposed || _isCleaned) return;

                // 获取导入后的统计信息
                var stats = await fuelCardTableService.GetStatisticsAsync(actualTableName);

                var message = $"✅ 导入成功!\n\n" +
                             $"📁 文件数: {FileCount}\n" +
                             $"📝 表名: {actualTableName}\n" +
                             $"📋 批次: {SelectedBatch?.Name}\n" +
                             $"📊 总记录数: {importedCount}\n" +
                             $"⛽ 加油记录: {FuelRecordCount}\n" +
                             $"💰 圈存记录: {DepositRecordCount}\n" +
                             $"💳 卡数: {stats.CardCount}\n" +
                             $"💰 总金额: {stats.TotalAmount:N2}元\n" +
                             $"⛽ 总升数: {stats.TotalFuelVolume:F2}L\n" +
                             $"{(tableExists ? "📌 数据已追加到现有表" : "📌 已创建新表")}\n" +
                             $"🕐 导入时间: {DateTime.Now:yyyy-MM-dd HH:mm:ss}";

                ShowImportStats = true;
                ImportStatsText = message;

                await ShowSuccessMessageAsync(message, "导入成功");

                SetStatus($"✅ 导入成功: {importedCount} 条记录 (加油:{FuelRecordCount}, 圈存:{DepositRecordCount}){(tableExists ? " (追加)" : "")}", new SolidColorBrush(Colors.Green));
                IsLoading = false;
                LoadingMessage = string.Empty;
            });
        }
        catch (Exception ex)
        {
            await ThreadingHelper.RunOnUIThreadAsync(async () =>
            {
                if (_disposed || _isCleaned) return;
                await ShowErrorMessageAsync($"导入失败: {ex.Message}", "导入失败");
                SetStatus($"❌ 导入失败: {ex.Message}", new SolidColorBrush(Colors.Red));
                IsLoading = false;
                LoadingMessage = string.Empty;
            });
        }
    }
    catch (Exception ex)
    {
        await ThreadingHelper.RunOnUIThreadAsync(async () =>
        {
            if (_disposed || _isCleaned) return;
            await ShowErrorMessageAsync($"导入失败: {ex.Message}", "导入失败");
            SetStatus($"❌ 导入失败: {ex.Message}", new SolidColorBrush(Colors.Red));
            IsLoading = false;
            LoadingMessage = string.Empty;
        });
    }
}
        
        #endregion

        #region 辅助方法

        private void Clear()
        {
            if (_disposed || _isCleaned) return;

            _ = ThreadingHelper.RunOnUIThreadAsync(() =>
            {
                if (_disposed || _isCleaned) return;
                FilePath = string.Empty;
                TableName = string.Empty;
                TableNameInfo = string.Empty;
                TableNameValidation = string.Empty;
                ShowValidation = false;
                _currentFileName = null;
                _isAutoGenerated = false;
                SelectedFiles?.Clear();
                CanImport = false;
                UseDictionary = false;
                FileCount = 0;
                TotalRecords = 0;
                CardCount = 0;
                TotalAmount = 0;
                TotalFuelVolume = 0;
                TotalAmountDisplay = "0.00";
                FuelRecordCount = 0;
                DepositRecordCount = 0;
                _allRecords.Clear();
                ShowImportStats = false;
                ImportStatsText = string.Empty;
                IsLoading = false;
                LoadingMessage = string.Empty;
                
                if (SelectedBatch != null)
                {
                    BatchInfo = $"已选批次: {SelectedBatch.Name}";
                }
                
                SetStatus(string.Empty, new SolidColorBrush(Colors.Transparent));
                ShowStatus = false;
            });
        }

        private void SetStatus(string message, IBrush color)
        {
            if (!Dispatcher.UIThread.CheckAccess())
            {
                Dispatcher.UIThread.Post(() => SetStatus(message, color));
                return;
            }

            StatusMessage = message;
            StatusColor = color;
            ShowStatus = !string.IsNullOrEmpty(message);
        }

        private void SetStatusSafe(string message, IBrush color)
        {
            _ = ThreadingHelper.RunOnUIThreadAsync(() =>
            {
                SetStatus(message, color);
            });
        }

        private async Task SetStatusAsync(string message, IBrush color)
        {
            await ThreadingHelper.RunOnUIThreadAsync(() =>
            {
                SetStatus(message, color);
            });
        }

        #endregion

        #region 对话框

        private Window? GetWindow()
        {
            if (_parentWindow != null) return _parentWindow;
            
            if (App.Current?.ApplicationLifetime is Avalonia.Controls.ApplicationLifetimes.IClassicDesktopStyleApplicationLifetime desktop)
            {
                return desktop.MainWindow ?? desktop.Windows.FirstOrDefault();
            }
            return null;
        }

        private async Task ShowMessageBoxAsync(string message, string title = "提示", MessageBoxIcon icon = MessageBoxIcon.None)
        {
            if (_disposed || _isCleaned) return;
            
            var window = GetWindow();
            if (window != null && window.IsVisible)
            {
                await MessageBox.ShowAsync(window, message, title, MessageBoxButtons.OK, icon);
            }
            else
            {
                await MessageBox.ShowAsync(message, title, MessageBoxButtons.OK, icon);
            }
        }

        private async Task<bool> ShowConfirmDialogAsync(string message, string title = "确认操作")
        {
            if (_disposed || _isCleaned) return false;
            
            var window = GetWindow();
            MessageBoxResult result;
            
            if (window != null && window.IsVisible)
            {
                result = await MessageBox.ShowAsync(window, message, title, MessageBoxButtons.YesNo, MessageBoxIcon.Question);
            }
            else
            {
                result = await MessageBox.ShowAsync(message, title, MessageBoxButtons.YesNo, MessageBoxIcon.Question);
            }
            
            return result == MessageBoxResult.Yes;
        }

        private async Task ShowSuccessMessageAsync(string message, string title = "成功")
        {
            await ShowMessageBoxAsync(message, title, MessageBoxIcon.Success);
        }

        private async Task ShowErrorMessageAsync(string message, string title = "错误")
        {
            await ShowMessageBoxAsync(message, title, MessageBoxIcon.Error);
        }

        private async Task ShowWarningMessageAsync(string message, string title = "警告")
        {
            await ShowMessageBoxAsync(message, title, MessageBoxIcon.Warning);
        }

        #endregion

        #region ICleanupPage 实现

        public void Cleanup()
        {
            if (_isCleaned) return;

            try
            {
                CancelCurrentOperation();

                _lock.Wait(TimeSpan.FromSeconds(2));
                try
                {
                    _subscriptions?.Dispose();

                    _ = ThreadingHelper.RunOnUIThreadAsync(() =>
                    {
                        try
                        {
                            Batches?.Clear();
                            DataDictionaries?.Clear();
                            SelectedFiles?.Clear();
                            SelectedBatch = null;
                            SelectedDictionary = null;
                            StatusMessage = string.Empty;
                            ShowStatus = false;
                            FilePath = string.Empty;
                            TableName = string.Empty;
                            TableNameInfo = string.Empty;
                            TableNameValidation = string.Empty;
                            ShowValidation = false;
                            _currentFileName = null;
                            _isAutoGenerated = false;
                            CanImport = false;
                            UseDictionary = false;
                            IsLoading = false;
                            LoadingMessage = string.Empty;
                            ShowImportStats = false;
                            ImportStatsText = string.Empty;
                            _allRecords.Clear();
                            FileCount = 0;
                            TotalRecords = 0;
                            CardCount = 0;
                            TotalAmount = 0;
                            TotalFuelVolume = 0;
                            TotalAmountDisplay = "0.00";
                            FuelRecordCount = 0;
                            DepositRecordCount = 0;
                        }
                        catch { }
                    });

                    _isCleaned = true;
                }
                finally
                {
                    try { _lock.Release(); } catch { }
                }
            }
            catch
            {
                _isCleaned = true;
            }
        }

        #endregion

        #region IDisposable 实现

        public void Dispose()
        {
            if (_disposed) return;

            try
            {
                Cleanup();
                _lock?.Dispose();
                _cts?.Dispose();
                _cts = null;
                _disposed = true;
            }
            catch
            {
                _disposed = true;
            }

            GC.SuppressFinalize(this);
        }

        #endregion
    }
}