using Avalonia.Controls;
using Avalonia.Platform.Storage;
using Avalonia.Media;
using ExcelToSQLite.Models;
using ExcelToSQLite.Services;
using ReactiveUI;
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.IO;
using System.Linq;
using System.Reactive;
using System.Reactive.Disposables;
using System.Reactive.Linq;
using System.Threading;
using System.Threading.Tasks;
using ExcelToSQLite.Helpers;
using Avalonia.Threading;

namespace ExcelToSQLite.ViewModels;

/// <summary>
/// JSON数据导入 ViewModel - 实现 ICleanupPage 和 IDisposable 以确保资源正确释放
/// </summary>
public class JsonDataViewModel : ReactiveObject, ICleanupPage, IDisposable
{
    private readonly JsonService? _jsonService;
    private readonly DatabaseService? _databaseService;
    private readonly AnalysisBatchService? _batchService;
    private readonly DataDictionaryService? _dictionaryService;
    private readonly SemaphoreSlim _lock = new SemaphoreSlim(1, 1);
    private readonly CompositeDisposable _subscriptions = new CompositeDisposable();
    private CancellationTokenSource? _cts;
    
    private Window? _parentWindow;
    private bool _disposed;
    private bool _isCleaned;
    private bool _isLoading;
    
    private string _filePath = string.Empty;
    private string _tableName = string.Empty;
    private ObservableCollection<ObservableCollection<object>>? _previewData;
    private string _previewInfo = string.Empty;
    private bool _canImport;
    private string _statusMessage = string.Empty;
    private IBrush _statusColor = new SolidColorBrush(Colors.Transparent);
    private bool _showStatus = false;
    
    private ObservableCollection<AnalysisBatch> _batches = new();
    private AnalysisBatch? _selectedBatch;
    private string _batchInfo = string.Empty;
    
    private ObservableCollection<DataDictionary> _dataDictionaries = new();
    private DataDictionary? _selectedDictionary;
    private string _dictionaryInfo = string.Empty;
    private bool _useDictionary = false;
    
    private string _tableNameInfo = string.Empty;
    private string _tableNameValidation = string.Empty;
    private IBrush _validationColor = new SolidColorBrush(Colors.Green);
    private bool _showValidation = false;
    private string? _currentFileName;
    private bool _isAutoGenerated = false;

    public JsonDataViewModel()
    {
        try
        {

            _jsonService = new JsonService();
            _databaseService = DatabaseService.Instance;
            _batchService = new AnalysisBatchService();
            _dictionaryService = new DataDictionaryService();
            
            SelectFileCommand = ReactiveCommand.CreateFromTask(SelectFileAsync);
            GenerateTableNameCommand = ReactiveCommand.Create(GenerateTableName);
            ImportCommand = ReactiveCommand.CreateFromTask(ImportAsync, this.WhenAnyValue(x => x.CanImport));
            ClearCommand = ReactiveCommand.Create(Clear);
            RefreshBatchesCommand = ReactiveCommand.CreateFromTask(LoadBatchesAsync);
            RefreshDictionariesCommand = ReactiveCommand.CreateFromTask(LoadDictionariesAsync);
            
            // ✅ 订阅命令异常
            SelectFileCommand.ThrownExceptions
                .ObserveOn(RxApp.MainThreadScheduler)
                .Subscribe(ex =>
                {
                    SetStatus($"选择文件失败: {ex.Message}", new SolidColorBrush(Colors.Red));
                })
                .DisposeWith(_subscriptions);

            ImportCommand.ThrownExceptions
                .ObserveOn(RxApp.MainThreadScheduler)
                .Subscribe(ex =>
                {
                    SetStatus($"导入失败: {ex.Message}", new SolidColorBrush(Colors.Red));
                })
                .DisposeWith(_subscriptions);

            PreviewData = new ObservableCollection<ObservableCollection<object>>();
            CanImport = false;
            
            // ✅ 监听表名变化，进行验证（使用 Rx 订阅）
            this.WhenAnyValue(x => x.TableName)
                .Subscribe(_ => ValidateTableName())
                .DisposeWith(_subscriptions);
            
            // ✅ 监听数据字典选择变化
            this.WhenAnyValue(x => x.SelectedDictionary)
                .Subscribe(_ => 
                {
                    if (UseDictionary && SelectedDictionary != null && !string.IsNullOrEmpty(_currentFileName))
                    {
                        GenerateTableName();
                    }
                })
                .DisposeWith(_subscriptions);
            
            // ✅ 监听是否使用数据字典
            this.WhenAnyValue(x => x.UseDictionary)
                .Subscribe(_ => 
                {
                    if (UseDictionary && SelectedDictionary != null && !string.IsNullOrEmpty(_currentFileName))
                    {
                        GenerateTableName();
                    }
                    else if (!UseDictionary && !string.IsNullOrEmpty(_currentFileName))
                    {
                        GenerateTableName();
                    }
                })
                .DisposeWith(_subscriptions);
            
            // ✅ 启动异步初始化
            _ = InitializeAsync();
            
        }
        catch (Exception ex)
        {
            SetStatusSafe($"初始化失败: {ex.Message}", new SolidColorBrush(Colors.Red));
        }
    }

    #region 属性

    public bool IsLoading
    {
        get => _isLoading;
        set => this.RaiseAndSetIfChanged(ref _isLoading, value);
    }

    public string FilePath
    {
        get => _filePath;
        set => this.RaiseAndSetIfChanged(ref _filePath, value);
    }

    public string TableName
    {
        get => _tableName;
        set
        {
            this.RaiseAndSetIfChanged(ref _tableName, value);
            if (!string.IsNullOrEmpty(value))
            {
                _isAutoGenerated = false;
            }
        }
    }

    public ObservableCollection<ObservableCollection<object>>? PreviewData
    {
        get => _previewData;
        set => this.RaiseAndSetIfChanged(ref _previewData, value);
    }

    public string PreviewInfo
    {
        get => _previewInfo;
        set => this.RaiseAndSetIfChanged(ref _previewInfo, value);
    }

    public bool CanImport
    {
        get => _canImport;
        set => this.RaiseAndSetIfChanged(ref _canImport, value);
    }

    public string StatusMessage
    {
        get => _statusMessage;
        set => this.RaiseAndSetIfChanged(ref _statusMessage, value);
    }

    public IBrush StatusColor
    {
        get => _statusColor;
        set => this.RaiseAndSetIfChanged(ref _statusColor, value);
    }

    public bool ShowStatus
    {
        get => _showStatus;
        set => this.RaiseAndSetIfChanged(ref _showStatus, value);
    }

    public ObservableCollection<AnalysisBatch> Batches
    {
        get => _batches;
        set => this.RaiseAndSetIfChanged(ref _batches, value);
    }

    public AnalysisBatch? SelectedBatch
    {
        get => _selectedBatch;
        set
        {
            this.RaiseAndSetIfChanged(ref _selectedBatch, value);
            if (value != null)
            {
                var createdTime = value.CreatedAt.ToString("yyyy-MM-dd HH:mm");
                BatchInfo = $"已选批次: {value.Name} (创建: {createdTime})";
                if (!string.IsNullOrEmpty(_currentFileName))
                {
                    GenerateTableName();
                }
            }
            else
            {
                BatchInfo = "请选择批次";
            }
        }
    }

    public string BatchInfo
    {
        get => _batchInfo;
        set => this.RaiseAndSetIfChanged(ref _batchInfo, value);
    }

    public ObservableCollection<DataDictionary> DataDictionaries
    {
        get => _dataDictionaries;
        set => this.RaiseAndSetIfChanged(ref _dataDictionaries, value);
    }

    public DataDictionary? SelectedDictionary
    {
        get => _selectedDictionary;
        set
        {
            this.RaiseAndSetIfChanged(ref _selectedDictionary, value);
            if (value != null)
            {
                DictionaryInfo = $"已选字典: {value.Name} (表名: {(string.IsNullOrEmpty(value.TableName) ? "使用文件名" : value.TableName)})";
                if (UseDictionary && !string.IsNullOrEmpty(_currentFileName))
                {
                    GenerateTableName();
                }
            }
            else
            {
                DictionaryInfo = "未选择数据字典";
            }
        }
    }

    public string DictionaryInfo
    {
        get => _dictionaryInfo;
        set => this.RaiseAndSetIfChanged(ref _dictionaryInfo, value);
    }

    public bool UseDictionary
    {
        get => _useDictionary;
        set
        {
            this.RaiseAndSetIfChanged(ref _useDictionary, value);
            if (!string.IsNullOrEmpty(_currentFileName))
            {
                GenerateTableName();
            }
        }
    }

    public string TableNameInfo
    {
        get => _tableNameInfo;
        set => this.RaiseAndSetIfChanged(ref _tableNameInfo, value);
    }

    public string TableNameValidation
    {
        get => _tableNameValidation;
        set => this.RaiseAndSetIfChanged(ref _tableNameValidation, value);
    }

    public IBrush ValidationColor
    {
        get => _validationColor;
        set => this.RaiseAndSetIfChanged(ref _validationColor, value);
    }

    public bool ShowValidation
    {
        get => _showValidation;
        set => this.RaiseAndSetIfChanged(ref _showValidation, value);
    }

    #endregion

    #region 命令

    public ReactiveCommand<Unit, Unit> SelectFileCommand { get; } = null!;
    public ReactiveCommand<Unit, Unit> GenerateTableNameCommand { get; } = null!;
    public ReactiveCommand<Unit, Unit> ImportCommand { get; } = null!;
    public ReactiveCommand<Unit, Unit> ClearCommand { get; } = null!;
    public ReactiveCommand<Unit, Unit> RefreshBatchesCommand { get; } = null!;
    public ReactiveCommand<Unit, Unit> RefreshDictionariesCommand { get; } = null!;

    #endregion

    #region 公共方法

    public void SetParentWindow(Window window)
    {
        _parentWindow = window;
    }

    #endregion

    #region 初始化

    private async Task InitializeAsync()
    {
        if (_disposed || _isCleaned) return;

        await _lock.WaitAsync();
        try
        {
            if (_disposed || _isCleaned) return;



            _cts = new CancellationTokenSource();
            var token = _cts.Token;

            var loadBatchesTask = LoadBatchesAsync();
            var loadDictionariesTask = LoadDictionariesAsync();

            await Task.WhenAll(loadBatchesTask, loadDictionariesTask);

            if (!token.IsCancellationRequested && !_disposed && !_isCleaned)
            {
                SetStatus("初始化完成", new SolidColorBrush(Colors.Green));
            }


        }
        catch (OperationCanceledException)
        {

        }
        catch (Exception ex)
        {

            await SetStatusAsync($"初始化失败: {ex.Message}", new SolidColorBrush(Colors.Red));
        }
        finally
        {
            _lock.Release();
        }
    }

    #endregion

    #region 数据加载

    private async Task LoadBatchesAsync()
    {
        if (_disposed || _isCleaned) return;
        if (_batchService == null) return;

        try
        {
            await ThreadingHelper.RunOnUIThreadAsync(() =>
            {
                if (_disposed || _isCleaned) return;
                IsLoading = true;
                SetStatus("正在加载批次...", new SolidColorBrush(Colors.Orange));
            });

            var list = await _batchService.GetAllAsync(1000);
            var sortedList = list.OrderByDescending(b => b.CreatedAt).ToList();
            
            await ThreadingHelper.RunOnUIThreadAsync(() =>
            {
                if (_disposed || _isCleaned) return;
                Batches = new ObservableCollection<AnalysisBatch>(sortedList);
                
                if (Batches.Count > 0)
                {
                    SelectedBatch = Batches[0];
                    BatchInfo = $"共 {Batches.Count} 个批次，已选择最新的批次: {SelectedBatch.Name}";
                
                    if (!string.IsNullOrEmpty(_currentFileName))
                    {
                        GenerateTableName();
                    }
                }
                else
                {
                    BatchInfo = "暂无批次，请创建批次";
                    SelectedBatch = null;
                }
                
                IsLoading = false;
                SetStatus("批次加载完成", new SolidColorBrush(Colors.Green));
            });
        }
        catch (Exception ex)
        {

            await ThreadingHelper.RunOnUIThreadAsync(() =>
            {
                if (_disposed || _isCleaned) return;
                SetStatus($"加载批次失败: {ex.Message}", new SolidColorBrush(Colors.Red));
                BatchInfo = "加载批次失败";
                SelectedBatch = null;
                IsLoading = false;
            });
        }
    }

    private async Task LoadDictionariesAsync()
    {
        if (_disposed || _isCleaned) return;
        if (_dictionaryService == null) return;

        try
        {
            await _dictionaryService.InitializeAsync();
            var list = await _dictionaryService.GetAllAsync();
            
            await ThreadingHelper.RunOnUIThreadAsync(() =>
            {
                if (_disposed || _isCleaned) return;
                DataDictionaries = new ObservableCollection<DataDictionary>(list);
                
                if (DataDictionaries.Count > 0)
                {
                    SelectedDictionary = DataDictionaries[0];
                    DictionaryInfo = $"已加载 {DataDictionaries.Count} 个数据字典";
                }
                else
                {
                    DictionaryInfo = "暂无数据字典，请先在数据字典页面创建";
                    SelectedDictionary = null;
                }
            });
        }
        catch (Exception ex)
        {

            await ThreadingHelper.RunOnUIThreadAsync(() =>
            {
                if (_disposed || _isCleaned) return;
                SetStatus($"加载数据字典失败: {ex.Message}", new SolidColorBrush(Colors.Red));
                DictionaryInfo = "加载数据字典失败";
            });
        }
    }

    #endregion

    #region 文件选择和预览

    private async Task SelectFileAsync()
    {
        if (_disposed || _isCleaned) return;

        CancelCurrentOperation();

        try
        {
            var window = GetWindow();
            if (window == null)
            {
                await ShowMessageBoxAsync("无法获取窗口句柄");
                return;
            }

            var filePath = await FileDialogHelper.OpenJsonFileAsync(window, "选择JSON文件");

            if (!string.IsNullOrEmpty(filePath))
            {
                await ThreadingHelper.RunOnUIThreadAsync(() =>
                {
                    if (_disposed || _isCleaned) return;
                    FilePath = filePath;
                    _currentFileName = Path.GetFileNameWithoutExtension(filePath);
                });
                await LoadPreviewAsync();
            }
        }
        catch (OperationCanceledException)
        {

        }
        catch (Exception ex)
        {
            await ShowMessageBoxAsync($"选择文件失败: {ex.Message}");

        }
    }

    private async Task LoadPreviewAsync()
    {
        if (_disposed || _isCleaned) return;
        if (_jsonService == null) return;

        CancelCurrentOperation();

        try
        {
            await ThreadingHelper.RunOnUIThreadAsync(() =>
            {
                if (_disposed || _isCleaned) return;
                IsLoading = true;
                SetStatus("正在加载预览...", new SolidColorBrush(Colors.Orange));
            });

            _cts = new CancellationTokenSource();
            var token = _cts.Token;

            var data = await _jsonService.ReadJsonAsync(FilePath);

            if (token.IsCancellationRequested || _disposed || _isCleaned) return;

            if (data == null || data.Count == 0)
            {
                await ShowMessageBoxAsync("文件为空或格式不正确");
                await ThreadingHelper.RunOnUIThreadAsync(() =>
                {
                    if (!_disposed && !_isCleaned) IsLoading = false;
                });
                return;
            }

            await ThreadingHelper.RunOnUIThreadAsync(() =>
            {
                if (_disposed || _isCleaned) return;

                var preview = new ObservableCollection<ObservableCollection<object>>();
                
                if (data.Count > 0 && data[0] != null)
                {
                    var headerRow = new ObservableCollection<object>();
                    foreach (var item in data[0])
                    {
                        headerRow.Add(item?.ToString() ?? string.Empty);
                    }
                    preview.Add(headerRow);
                }

                int maxRows = Math.Min(data.Count - 1, 20);
                for (int i = 1; i <= maxRows; i++)
                {
                    var row = new ObservableCollection<object>();
                    if (data[i] != null)
                    {
                        foreach (var item in data[i])
                        {
                            row.Add(item?.ToString() ?? string.Empty);
                        }
                    }
                    preview.Add(row);
                }

                PreviewData = preview;
                
                int totalRows = data.Count - 1;
                int totalCols = data[0]?.Count ?? 0;
                PreviewInfo = $"共 {totalRows} 行数据，{totalCols} 列";
                
                GenerateTableName();
                CanImport = true;
                IsLoading = false;
                SetStatus($"文件加载成功: {Path.GetFileName(FilePath)}", new SolidColorBrush(Colors.Green));
            });
        }
        catch (OperationCanceledException)
        {

            await ThreadingHelper.RunOnUIThreadAsync(() =>
            {
                if (!_disposed && !_isCleaned)
                {
                    IsLoading = false;
                    SetStatus("预览已取消", new SolidColorBrush(Colors.Orange));
                }
            });
        }
        catch (Exception ex)
        {

            await ThreadingHelper.RunOnUIThreadAsync(() =>
            {
                if (_disposed || _isCleaned) return;
                CanImport = false;
                IsLoading = false;
                SetStatus($"加载失败: {ex.Message}", new SolidColorBrush(Colors.Red));
            });
            await ShowMessageBoxAsync($"加载预览失败: {ex.Message}");
        }
    }

    #endregion

    #region 取消操作

    private void CancelCurrentOperation()
    {
        try
        {
            _cts?.Cancel();
            _cts?.Dispose();
            _cts = null;
        }
        catch
        {

        }
    }

    #endregion

    #region 表名生成

    private void GenerateTableName()
    {
        if (_disposed || _isCleaned) return;

        if (string.IsNullOrEmpty(FilePath) || SelectedBatch == null)
        {
            TableName = string.Empty;
            TableNameInfo = "请选择文件和批次后自动生成表名";
            return;
        }

        var fileName = Path.GetFileNameWithoutExtension(FilePath);
        var tablePrefix = SelectedBatch.TablePrefix;
        string generatedName;

        if (UseDictionary && SelectedDictionary != null)
        {
            generatedName = PublicEvent.GetFormatFilename(tablePrefix, fileName, SelectedDictionary.TableName);
        }
        else
        {
            generatedName = PublicEvent.GetFormatFilename(tablePrefix, fileName);
        }

        TableName = generatedName;
        _isAutoGenerated = true;
        ValidateTableName();
    }

    private void ValidateTableName()
    {
        if (_disposed || _isCleaned) return;

        if (string.IsNullOrEmpty(TableName))
        {
            TableNameValidation = "⚠️ 表名不能为空";
            ValidationColor = new SolidColorBrush(Colors.Orange);
            ShowValidation = true;
            return;
        }

        var invalidChars = new[] { ' ', '-', '/', '\\', ':', '*', '?', '"', '<', '>', '|', '\'', ';' };
        if (TableName.IndexOfAny(invalidChars) >= 0)
        {
            TableNameValidation = "❌ 表名包含非法字符，请使用字母、数字和下划线";
            ValidationColor = new SolidColorBrush(Colors.Red);
            ShowValidation = true;
            return;
        }

        if (!char.IsLetter(TableName[0]))
        {
            TableNameValidation = "⚠️ 表名应以字母开头";
            ValidationColor = new SolidColorBrush(Colors.Orange);
            ShowValidation = true;
            return;
        }

        if (TableName.Length > 60)
        {
            TableNameValidation = $"⚠️ 表名过长 ({TableName.Length}/60)，建议缩短";
            ValidationColor = new SolidColorBrush(Colors.Orange);
            ShowValidation = true;
            return;
        }

        var keywords = new[] { "SELECT", "INSERT", "UPDATE", "DELETE", "DROP", "CREATE", "ALTER", "TABLE" };
        if (keywords.Contains(TableName.ToUpper()))
        {
            TableNameValidation = "⚠️ 表名不能是SQL关键字";
            ValidationColor = new SolidColorBrush(Colors.Orange);
            ShowValidation = true;
            return;
        }

        if (_isAutoGenerated)
        {
            TableNameValidation = "✅ 表名有效 (自动生成)";
        }
        else
        {
            TableNameValidation = "✅ 表名有效 (已自定义)";
        }
        ValidationColor = new SolidColorBrush(Colors.Green);
        ShowValidation = true;
    }

    #endregion

    #region 导入

    private async Task ImportAsync()
    {
        if (_disposed || _isCleaned) return;
        if (IsLoading) return;
        if (_jsonService == null || _databaseService == null) return;

        try
        {
            if (string.IsNullOrEmpty(FilePath))
            {
                await ShowMessageBoxAsync("请先选择JSON文件");
                return;
            }

            if (SelectedBatch == null)
            {
                await ShowMessageBoxAsync("请先选择分析批次");
                return;
            }

            if (string.IsNullOrEmpty(TableName))
            {
                await ShowMessageBoxAsync("请输入表名或点击'自动生成'");
                return;
            }

            if (TableName.IndexOfAny(new[] { ' ', '-', '/', '\\', ':', '*', '?', '"', '<', '>', '|', '\'', ';' }) >= 0)
            {
                await ShowMessageBoxAsync("表名包含非法字符，请使用字母、数字和下划线");
                return;
            }

            if (!char.IsLetter(TableName[0]))
            {
                await ShowMessageBoxAsync("表名应以字母开头");
                return;
            }

            var confirmMessage = $"📊 确认导入数据\n\n" +
                                $"📁 文件: {Path.GetFileName(FilePath)}\n" +
                                $"📋 批次: {SelectedBatch.Name}\n" +
                                $"📝 表名: {TableName}\n" +
                                $"📅 创建时间: {SelectedBatch.CreatedAt:yyyy-MM-dd HH:mm}\n";

            if (UseDictionary && SelectedDictionary != null)
            {
                confirmMessage += $"📚 数据字典: {SelectedDictionary.Name}\n";
                if (!string.IsNullOrEmpty(SelectedDictionary.TableName))
                {
                    confirmMessage += $"🗄️ 字典表名: {SelectedDictionary.TableName}\n";
                }
            }

            confirmMessage += $"\n确认继续导入？";

            var confirm = await ShowConfirmDialogAsync(confirmMessage);
            if (!confirm) return;

            await ThreadingHelper.RunOnUIThreadAsync(() =>
            {
                if (_disposed || _isCleaned) return;
                IsLoading = true;
                SetStatus("正在导入数据...", new SolidColorBrush(Colors.Orange));
            });

            var data = await _jsonService.ReadJsonAsync(FilePath);
            
            if (data == null || data.Count <= 1)
            {
                await ShowMessageBoxAsync("没有数据可导入");
                await ThreadingHelper.RunOnUIThreadAsync(() =>
                {
                    if (!_disposed && !_isCleaned) IsLoading = false;
                });
                return;
            }

            var columns = new List<string>();
            if (data.Count > 0 && data[0] != null)
            {
                foreach (var col in data[0])
                {
                    var colName = col?.ToString()?.Trim() ?? $"Column{columns.Count + 1}";
                    columns.Add(colName);
                }
            }

            var emptyColumns = columns.Where(c => string.IsNullOrEmpty(c)).ToList();
            if (emptyColumns.Any())
            {
                await ShowMessageBoxAsync($"列名包含空值，请检查JSON文件。");
                await ThreadingHelper.RunOnUIThreadAsync(() =>
                {
                    if (!_disposed && !_isCleaned) IsLoading = false;
                });
                return;
            }

            if (columns.Any(c => c.Equals("Id", StringComparison.OrdinalIgnoreCase)))
            {
                await ShowMessageBoxAsync("列名中不能包含 'Id'，因为它是系统保留字段。请修改列名后再试。");
                await ThreadingHelper.RunOnUIThreadAsync(() =>
                {
                    if (!_disposed && !_isCleaned) IsLoading = false;
                });
                return;
            }

            await _databaseService.CreateTableAsync(TableName, columns);

            var rows = data.Skip(1).ToList();
            await _databaseService.InsertDataAsync(TableName, columns, rows);

            await ThreadingHelper.RunOnUIThreadAsync(async () =>
            {
                if (_disposed || _isCleaned) return;

                var message = $"✅ 导入成功!\n\n" +
                             $"📝 表名: {TableName}\n" +
                             $"📋 批次: {SelectedBatch.Name}\n" +
                             $"📊 导入行数: {rows.Count}\n" +
                             $"📑 列数: {columns.Count}\n" +
                             $"🕐 导入时间: {DateTime.Now:yyyy-MM-dd HH:mm:ss}";

                if (UseDictionary && SelectedDictionary != null)
                {
                    message += $"\n📚 数据字典: {SelectedDictionary.Name}";
                }
                
                await ShowMessageBoxAsync(message);
                
                PreviewInfo = $"✅ 已导入 {rows.Count} 行数据到表 {TableName} (批次: {SelectedBatch.Name})";
                SetStatus($"✅ 导入成功: {rows.Count} 行数据", new SolidColorBrush(Colors.Green));
                IsLoading = false;
            });
        }
        catch (Exception ex)
        {

            await ThreadingHelper.RunOnUIThreadAsync(async () =>
            {
                if (_disposed || _isCleaned) return;
                var errorMsg = $"导入失败: {ex.Message}";
                await ShowMessageBoxAsync(errorMsg);
                SetStatus($"❌ {errorMsg}", new SolidColorBrush(Colors.Red));
                IsLoading = false;
            });
        }
    }

    #endregion

    #region UI辅助方法

    private void Clear()
    {
        if (_disposed || _isCleaned) return;

        _ = ThreadingHelper.RunOnUIThreadAsync(() =>
        {
            if (_disposed || _isCleaned) return;
            FilePath = string.Empty;
            TableName = string.Empty;
            TableNameInfo = string.Empty;
            TableNameValidation = string.Empty;
            ShowValidation = false;
            _currentFileName = null;
            _isAutoGenerated = false;
            UseDictionary = false;
            PreviewData?.Clear();
            PreviewInfo = string.Empty;
            CanImport = false;
            IsLoading = false;
            
            if (SelectedBatch != null)
            {
                BatchInfo = $"已选批次: {SelectedBatch.Name}";
            }
            
            SetStatus(string.Empty, new SolidColorBrush(Colors.Transparent));
            ShowStatus = false;
        });
    }

    private void SetStatus(string message, IBrush color)
    {
        if (!Dispatcher.UIThread.CheckAccess())
        {
            Dispatcher.UIThread.Post(() => SetStatus(message, color));
            return;
        }

        StatusMessage = message;
        StatusColor = color;
        ShowStatus = !string.IsNullOrEmpty(message);
    }

    private void SetStatusSafe(string message, IBrush color)
    {
        _ = ThreadingHelper.RunOnUIThreadAsync(() =>
        {
            SetStatus(message, color);
        });
    }

    private async Task SetStatusAsync(string message, IBrush color)
    {
        await ThreadingHelper.RunOnUIThreadAsync(() =>
        {
            SetStatus(message, color);
        });
    }

    #endregion

    #region 对话框

    private Window? GetWindow()
    {
        if (_parentWindow != null)
            return _parentWindow;

        if (App.Current?.ApplicationLifetime is Avalonia.Controls.ApplicationLifetimes.IClassicDesktopStyleApplicationLifetime desktop)
        {
            return desktop.MainWindow ?? desktop.Windows.FirstOrDefault();
        }

        return null;
    }

    private async Task ShowMessageBoxAsync(string message)
    {
        if (_disposed || _isCleaned) return;

        var window = GetWindow();
        if (window == null) return;

        await MessageBox.ShowAsync(
            window,
            message,
            "提示",
            MessageBoxButtons.OK,
            MessageBoxIcon.Information
        );
    }

    private async Task<bool> ShowConfirmDialogAsync(string message)
    {
        
        if (_disposed || _isCleaned) return false;

        var window = GetWindow();
        if (window == null) return false;

        // 使用 MessageBox 显示确认对话框
        var result = await MessageBox.ShowAsync(
            window,
            message,
            "确认导入",
            MessageBoxButtons.YesNo,
            MessageBoxIcon.Question
        );

        return result == MessageBoxResult.Yes;
    }

    #endregion

    #region ICleanupPage 实现

    /// <summary>
    /// 清理资源 - 在 View 卸载时调用
    /// </summary>
    public void Cleanup()
    {
        if (_isCleaned) return;

        try
        {


            CancelCurrentOperation();

            _lock.Wait(TimeSpan.FromSeconds(2));
            try
            {
                _subscriptions?.Dispose();

                _ = ThreadingHelper.RunOnUIThreadAsync(() =>
                {
                    try
                    {
                        PreviewData?.Clear();
                        Batches?.Clear();
                        DataDictionaries?.Clear();
                        SelectedBatch = null;
                        SelectedDictionary = null;
                        StatusMessage = string.Empty;
                        ShowStatus = false;
                        FilePath = string.Empty;
                        TableName = string.Empty;
                        TableNameInfo = string.Empty;
                        TableNameValidation = string.Empty;
                        ShowValidation = false;
                        _currentFileName = null;
                        _isAutoGenerated = false;
                        PreviewInfo = string.Empty;
                        CanImport = false;
                        UseDictionary = false;
                        IsLoading = false;
                    }
                    catch { }
                });

                _isCleaned = true;

            }
            finally
            {
                try { _lock.Release(); } catch { }
            }
        }
        catch
        {

            _isCleaned = true;
        }
    }

    #endregion

    #region IDisposable 实现

    public void Dispose()
    {
        if (_disposed) return;

        try
        {


            Cleanup();

            _lock?.Dispose();
            _cts?.Dispose();
            _cts = null;

            SelectFileCommand?.Dispose();
            GenerateTableNameCommand?.Dispose();
            ImportCommand?.Dispose();
            ClearCommand?.Dispose();
            RefreshBatchesCommand?.Dispose();
            RefreshDictionariesCommand?.Dispose();

            _disposed = true;

        }
        catch 
        {
            _disposed = true;
        }

        GC.SuppressFinalize(this);
    }

    #endregion
}